<?php
require_once dirname(__DIR__) . '/_bootstrap.php';

// Balance endpoints always answer from the database (no saved snapshot).

$user = api_primary_user();
$payload = [
        'data' => [
            'balance' => (float) $user['wallet_balance'],
            'realName' => '',
            'amountCoding' => 4.11,
            'hasWithdrawPassword' => false,
            'withdrawCategoryList' => [
                [
                    'id' => 400078,
                    'tenantId' => 6006,
                    'withdrawType' => 'BankCard',
                    'name' => 'BankCard',
                    'iconUrl' => '/img/6006/bankLogo/053755188-34816-file_20260502173755187.webp',
                    'selectedIconUrl' => '/img/6006/bankLogo/053757456-34817-file_20260502173757455.webp',
                    'userMaxBindCount' => 1,
                    'maxWithdrawTimes' => 5,
                    'minAmount' => 110,
                    'maxAmount' => 50000,
                    'feeAmountRangeMin' => 0,
                    'feeAmountRangeMax' => 0,
                    'feeType' => 0,
                    'feePercent' => 0,
                    'fee' => 0,
                    'allowStartTime' => '00:00',
                    'allowEndTime' => '23:59',
                    'sort' => 200,
                    'state' => 1,
                ],
                [
                    'id' => 400080,
                    'tenantId' => 6006,
                    'withdrawType' => 'UPI',
                    'name' => 'UPI',
                    'iconUrl' => '/img/6006/bankLogo/115634796-38755-file_20260511115634703.webp',
                    'selectedIconUrl' => '/img/6006/bankLogo/115636400-38756-file_20260511115636396.webp',
                    'userMaxBindCount' => 1,
                    'maxWithdrawTimes' => 5,
                    'minAmount' => 100,
                    'maxAmount' => 50000,
                    'feeAmountRangeMin' => 0,
                    'feeAmountRangeMax' => 0,
                    'feeType' => 0,
                    'feePercent' => 0,
                    'fee' => 0,
                    'allowStartTime' => '00:00',
                    'allowEndTime' => '23:59',
                    'sort' => 150,
                    'state' => 1,
                ],
                [
                    'id' => 400079,
                    'tenantId' => 6006,
                    'withdrawType' => 'USDT',
                    'name' => 'USDT',
                    'iconUrl' => '/img/6006/bankLogo/080246522-38675-file_20260511080246521.webp',
                    'selectedIconUrl' => '/img/6006/bankLogo/080246327-38674-file_20260511080246326.webp',
                    'userMaxBindCount' => 1,
                    'maxWithdrawTimes' => 3,
                    'minAmount' => 1000,
                    'maxAmount' => 1000000,
                    'feeAmountRangeMin' => 0,
                    'feeAmountRangeMax' => 0,
                    'feeType' => 0,
                    'feePercent' => 0,
                    'fee' => 0,
                    'allowStartTime' => '00:00',
                    'allowEndTime' => '23:59',
                    'sort' => 100,
                    'state' => 1,
                ],
                [
                    'id' => 400082,
                    'tenantId' => 6006,
                    'withdrawType' => 'ARPay',
                    'name' => 'ARPay',
                    'iconUrl' => '/img/6006/bankLogo/105025481-43516-file_20260523105025479.webp',
                    'selectedIconUrl' => '/img/6006/bankLogo/105027211-43517-file_20260523105027210.webp',
                    'userMaxBindCount' => null,
                    'maxWithdrawTimes' => 3,
                    'minAmount' => 100,
                    'maxAmount' => 50000,
                    'feeAmountRangeMin' => 0,
                    'feeAmountRangeMax' => 0,
                    'feeType' => 0,
                    'feePercent' => 0,
                    'fee' => 0,
                    'allowStartTime' => '00:00',
                    'allowEndTime' => '23:59',
                    'sort' => 0,
                    'state' => 1,
                ],
            ],
            'addWalletNeedEmailVerifyCode' => false,
            'addWalletNeedSmsVerifyCode' => true,
            'userTodayWithdrawFreeCount' => 0,
            'userTodayWithdrawAmount' => -1,
            'userTodayWithdrawCount' => -1,
            'isWithdrawAmountFixed' => false,
            'fixedWithdrawAmountList' => [],
            'isWithdrawAmountAllowInput' => false,
            'pendingCompensationAmount' => 0,
            'isNeedWithdrawPassword' => false,
        ],
        'code' => 0,
        'msg' => 'Succeed',
        'msgCode' => 0,
        'serverTime' => 1780315514682,
    ];

api_refresh_times($payload);
api_emit($payload);
