<?php
declare(strict_types=1);

require_once __DIR__ . '/lib.php';
require_once __DIR__ . '/actions.php';

dw_admin_session_start();
$conn = db();
if (!$conn) {
    http_response_code(503);
    echo '<!doctype html><meta charset="utf-8"><title>Dhani Win Admin</title><style>body{font-family:sans-serif;padding:40px;background:#f4f7f5}div{max-width:680px;margin:auto;background:white;padding:28px;border-radius:16px}</style><div><h1>Database unavailable</h1><p>Check the database values in <code>api/_core/config.php</code>, import <code>database.sql</code>, and reload this page.</p></div>';
    exit;
}

$loginError = '';
if (($_SERVER['REQUEST_METHOD'] ?? 'GET') === 'POST' && ($_POST['action'] ?? '') === 'login') {
    [$ok, $message] = dw_admin_login($conn, dw_post_string('username'), (string)($_POST['password'] ?? ''));
    if ($ok) dw_redirect('dashboard');
    $loginError = $message;
}

$admin = dw_admin_user($conn);
if (!$admin):
?><!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Dhani Win Admin Login</title><link rel="stylesheet" href="assets/admin.css?v=34"></head>
<body class="login-page">
<main class="login-card">
  <div class="login-logo"><div class="brand-mark">DW</div><div><h1>Dhani Win</h1><p>Secure operations console</p></div></div>
  <?php if ($loginError): ?><div class="flash error"><?=dw_h($loginError)?></div><?php endif; ?>
  <form method="post" autocomplete="off">
    <input type="hidden" name="action" value="login">
    <div class="field"><label>Admin username</label><input class="input" name="username" required autofocus autocomplete="username"></div>
    <div class="field"><label>Password</label><input class="input" type="password" name="password" required autocomplete="current-password"></div>
    <button class="btn primary" type="submit">Sign in securely</button>
  </form>
  <p class="login-note">Rate-limited login, secure session cookie and complete action audit are enabled. Change the installation password immediately after first login.</p>
</main></body></html>
<?php exit; endif;

$permissions = dw_admin_permissions($conn, $admin);
if (($_SERVER['REQUEST_METHOD'] ?? 'GET') === 'POST' && ($_POST['action'] ?? '') === 'logout') {
    try { dw_verify_csrf(); dw_admin_audit($conn,$admin,'admin_logout','admin',(int)$admin['id']); } catch (Throwable $ignored) {}
    dw_admin_logout();
    header('Location: index.php');
    exit;
}
if (($_SERVER['REQUEST_METHOD'] ?? 'GET') === 'POST') {
    try {
        dw_admin_handle_post($conn, $admin, $permissions);
    } catch (Throwable $e) {
        dw_flash('error', $e->getMessage());
        dw_redirect(dw_allowed_page(dw_post_string('return_page', 'dashboard')));
    }
}

$page = dw_allowed_page((string)($_GET['page'] ?? 'dashboard'));
$pagePermissions = ['ledger'=>'finance','recharges'=>'recharges','withdrawals'=>'withdrawals','wagers'=>'wagers','users'=>'users','games'=>'games','providers'=>'games','wingo'=>'wingo','gifts'=>'gifts','payments'=>'payments','content'=>'content','vip'=>'vip','tasks'=>'tasks','wheels'=>'wheels','support'=>'support','agents'=>'agents','risk'=>'risk','settings'=>'settings','admins'=>'admins','audit'=>'audit','system'=>'system'];
if (isset($pagePermissions[$page]) && !dw_can($permissions, $pagePermissions[$page])) {
    $page = 'dashboard';
    dw_flash('error', 'You do not have permission to open that module.');
}

function dw_meta(string $page): void {
    echo '<input type="hidden" name="_csrf" value="'.dw_h(dw_csrf_token()).'"><input type="hidden" name="return_page" value="'.dw_h($page).'">';
}
function dw_badge(string $status): string {
    $s=strtolower($status);$class=in_array($s,['approved','payed','active','success','received','answered','resolved','completed','pass'],true)?'':(in_array($s,['pending','wait','pendingreview','processing','reviewing','open'],true)?'warn':(in_array($s,['rejected','cancel','disabled','failed','suspended','critical'],true)?'danger':'gray'));
    return '<span class="badge '.$class.'">'.dw_h($status).'</span>';
}
function dw_pages(int $total,int $size,int $current,array $query): void {
    $count=(int)ceil($total/max(1,$size));if($count<=1)return;echo '<nav class="pagination">';
    $start=max(1,$current-2);$end=min($count,$current+2);
    if($current>1){$query['p']=$current-1;echo '<a href="?'.dw_h(http_build_query($query)).'">‹</a>';}
    for($i=$start;$i<=$end;$i++){$query['p']=$i;echo '<a class="'.($i===$current?'active':'').'" href="?'.dw_h(http_build_query($query)).'">'.$i.'</a>';}
    if($current<$count){$query['p']=$current+1;echo '<a href="?'.dw_h(http_build_query($query)).'">›</a>';}echo '</nav>';
}
function dw_wallet_display(array $row): string {
    $json=(string)($row['wallet_snapshot']?:$row['wallet_info']??'');$data=json_decode($json,true);if(!is_array($data))return dw_h(dw_mask_account($json));
    $account=(string)($data['accountNo']??$data['upiId']??$data['usdtAddress']??'');$name=(string)($data['bankName']??$data['walletName']??'');
    return dw_h($name).' <span class="mono">'.dw_h(dw_mask_account($account)).'</span>';
}

if (!empty($_GET['export'])) {
    $export=(string)$_GET['export'];$rows=[];$headers=[];$filename='dhaniwin-'.$export.'-'.date('Ymd-His').'.csv';
    if($export==='users'){dw_require_permission($permissions,'users');$headers=['ID','Username','Mobile','Nickname','Balance','VIP','Status','Created'];foreach(dw_rows($conn,"SELECT id,username,mobile,nickname,balance,vip_level,status,created_at FROM users WHERE role='user' ORDER BY id DESC LIMIT 10000") as $r)$rows[]=[(int)$r['id'],$r['username'],$r['mobile'],$r['nickname'],$r['balance'],$r['vip_level'],$r['status'],$r['created_at']];}
    elseif($export==='recharges'){dw_require_permission($permissions,'recharges');$headers=['Order','User','Amount','Gift','Type','Status','UTR','Created'];foreach(dw_rows($conn,"SELECT r.*,u.username FROM recharge_orders r LEFT JOIN users u ON u.id=r.user_id ORDER BY r.id DESC LIMIT 10000") as $r)$rows[]=[$r['order_no'],$r['username'],$r['amount'],$r['gift_amount'],$r['recharge_type'],$r['status'],$r['utr'],$r['created_at']];}
    elseif($export==='withdrawals'){dw_require_permission($permissions,'withdrawals');$headers=['Order','User','Amount','Method','Status','Reserved','Note','Created'];foreach(dw_rows($conn,"SELECT w.*,u.username FROM withdraw_requests w LEFT JOIN users u ON u.id=w.user_id ORDER BY w.id DESC LIMIT 10000") as $r)$rows[]=[$r['order_no'],$r['username'],$r['amount'],$r['method'],$r['status'],$r['is_reserved'],$r['admin_note'],$r['created_at']];}
    elseif($export==='ledger'){dw_require_permission($permissions,'finance');$headers=['Record','Order','User','Type','Amount','Before','After','Description','Created'];foreach(dw_rows($conn,"SELECT f.*,u.username FROM financial_records f LEFT JOIN users u ON u.id=f.user_id ORDER BY f.id DESC LIMIT 10000") as $r)$rows[]=[$r['record_no'],$r['order_no'],$r['username'],$r['type'],$r['amount'],$r['balance_before'],$r['back_amount'],$r['description'],$r['created_at']];}
    elseif($export==='audit'){dw_require_permission($permissions,'audit');$headers=['ID','Admin ID','Action','Target','Target ID','IP','Data','Created'];foreach(dw_rows($conn,"SELECT * FROM admin_audit_logs ORDER BY id DESC LIMIT 10000") as $r)$rows[]=[$r['id'],$r['admin_user_id'],$r['action'],$r['target_type'],$r['target_id'],$r['ip'],$r['data_json'],$r['created_at']];}
    else throw new RuntimeException('Unknown export.');
    dw_admin_audit($conn,$admin,'csv_export',$export,0,['rows'=>count($rows)]);
    dw_csv_download($filename,$headers,$rows);
}

$titles=['dashboard'=>'Dashboard Overview','users'=>'Manage Users','recharges'=>'Deposit Update','withdrawals'=>'Withdraw Apply','ledger'=>'Balance Record','wagers'=>'Turnover Control','games'=>'Games','providers'=>'Game Providers','wingo'=>'Game Result Control','gifts'=>'Gift Code','payments'=>'UPI / USDT Methods','content'=>'Content','vip'=>'VIP Levels','tasks'=>'Bonus Manage','wheels'=>'Wheel Control','support'=>'Support','agents'=>'Agent User & Daily Salary','risk'=>'Check Same IP','settings'=>'Site Maintenance','admins'=>'Admin Manage','audit'=>'Audit Log','system'=>'System Health'];
$nav=[
 'Overview'=>[['dashboard','Dashboard','◉','dashboard']],
 'WinGo Manager'=>[
   ['wingo','WinGo 30 Sec','◈','wingo','?page=wingo&game=WinGo_30S'],
   ['wingo','WinGo 1 Min','◈','wingo','?page=wingo&game=WinGo_1M'],
   ['wingo','WinGo 3 Min','◈','wingo','?page=wingo&game=WinGo_3M'],
   ['wingo','WinGo 5 Min','◈','wingo','?page=wingo&game=WinGo_5M']
 ],
 'K3 Manager'=>[
   ['wingo','K3 1 Min','⚄','wingo','?page=wingo&game=K3_1M'],
   ['wingo','K3 3 Min','⚄','wingo','?page=wingo&game=K3_3M'],
   ['wingo','K3 5 Min','⚄','wingo','?page=wingo&game=K3_5M'],
   ['wingo','K3 10 Min','⚄','wingo','?page=wingo&game=K3_10M']
 ],
 '5D Manager'=>[
   ['wingo','5D 1 Min','▦','wingo','?page=wingo&game=D5_1M'],
   ['wingo','5D 3 Min','▦','wingo','?page=wingo&game=D5_3M'],
   ['wingo','5D 5 Min','▦','wingo','?page=wingo&game=D5_5M'],
   ['wingo','5D 10 Min','▦','wingo','?page=wingo&game=D5_10M']
 ],
 'TRX Manager'=>[
   ['wingo','TRX 1 Min','◆','wingo','?page=wingo&game=TrxWinGo_1M'],
   ['wingo','TRX 3 Min','◆','wingo','?page=wingo&game=TrxWinGo_3M'],
   ['wingo','TRX 5 Min','◆','wingo','?page=wingo&game=TrxWinGo_5M'],
   ['wingo','TRX 10 Min','◆','wingo','?page=wingo&game=TrxWinGo_10M']
 ],
 'Finance'=>[
   ['users','Manage Users','♙','users'],['users','Banned Users','⊘','users','?page=users&status=suspended'],
   ['recharges','Deposit Update','↓','recharges'],['withdrawals','Withdraw Apply','↑','withdrawals','?page=withdrawals&status=pending'],
   ['withdrawals','UPI Withdraw','₹','withdrawals','?page=withdrawals&method=UPI'],['withdrawals','Withdraw Sent','✓','withdrawals','?page=withdrawals&status=approved'],
   ['withdrawals','Withdraw Reject','×','withdrawals','?page=withdrawals&status=rejected'],['ledger','Balance Record','≋','finance'],['wagers','Turnover Control','◫','wagers'],
   ['payments','Add UPI / USDT','₮','payments']
 ],
 'Bonus & Agent'=>[['tasks','Bonus Manage','★','tasks'],['agents','Daily Salary','₹','agents'],['gifts','Gift Code','✦','gifts'],['wheels','Wheel Control','◉','wheels'],['agents','Agent User','♧','agents']],
 'Support'=>[['support','Support','☏','support'],['content','Content','▤','content'],['vip','VIP Levels','♛','vip'],['games','Game List','◇','games'],['providers','Game Providers','⇄','games']],
 'Admin Manage'=>[['admins','Add Admin','＋','admins'],['admins','Admin Password','⚿','admins'],['risk','Check Same IP','⚑','risk'],['settings','Site Maintenance','⚙','settings'],['audit','Audit Log','⌁','audit'],['system','System Health','◌','system']]
];
$flash=dw_take_flash();
?><!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title><?=dw_h($titles[$page])?> · Dhani Win Admin</title><link rel="stylesheet" href="assets/admin.css?v=34"></head>
<body><div class="layout">
<aside class="sidebar">
 <div class="brand"><div class="brand-mark">DW</div><div><strong>Dhani Win</strong><small>Advanced Admin v34</small></div></div>
 <div class="author-card"><div class="author-avatar">TL</div><strong>Made BY Developer Boy</strong><span>Super Admin</span></div>
 <?php foreach($nav as $group=>$items): ?><div class="nav-label"><?=dw_h($group)?></div><nav class="nav"><?php foreach($items as $item):[$key,$label,$icon,$perm]=$item;if(!dw_can($permissions,$perm))continue;$url=$item[4]??('?page='.$key);?><a class="<?=$page===$key?'active':''?>" href="<?=dw_h($url)?>"><span class="icon"><?=dw_h($icon)?></span><?=dw_h($label)?></a><?php endforeach;?></nav><?php endforeach;?>
 <a class="website-link" href="../" target="_blank" rel="noopener">↗ Go To Website</a>
</aside>
<main class="main">
 <header class="topbar"><div style="display:flex;gap:10px;align-items:center"><button class="btn ghost mobile-toggle" data-sidebar-toggle>☰</button><h1><?=dw_h($titles[$page])?></h1></div><div class="topbar-actions"><span class="admin-chip"><?=dw_h($admin['nickname']?:$admin['username'])?></span><form method="post"><?php dw_meta($page)?><input type="hidden" name="action" value="logout"><button class="btn ghost" type="submit">Sign out</button></form></div></header>
 <div class="content">
 <?php if($flash):?><div class="flash <?=dw_h($flash['type'])?>"><?=dw_h($flash['message'])?></div><?php endif;?>
 <?php if((int)$admin['must_change_password']===1):?><div class="notice"><strong>Temporary password detected.</strong> Change it now; all other admin actions are locked.</div>
 <section class="panel"><div class="panel-head"><h2>Change admin password</h2></div><div class="panel-body"><form method="post" class="form-grid"><?php dw_meta('dashboard')?><input type="hidden" name="action" value="change_own_password"><div class="field"><label>Current password</label><input class="input" type="password" name="current_password" required></div><div></div><div class="field"><label>New password (10+ chars)</label><input class="input" type="password" name="new_password" required></div><div class="field"><label>Confirm password</label><input class="input" type="password" name="confirm_password" required></div><div class="wide"><button class="btn primary">Update password</button></div></form></div></section>
 <?php else:

 if($page==='dashboard'):
   $totalUsers=(int)dw_scalar($conn,"SELECT COUNT(*) FROM users WHERE role='user'");
   $userWallet=(float)dw_scalar($conn,"SELECT COALESCE(SUM(balance),0) FROM users WHERE role='user'");
   $todayRecharge=(float)dw_scalar($conn,"SELECT COALESCE(SUM(amount+gift_amount),0) FROM recharge_orders WHERE status='Payed' AND created_at>=CURDATE()");
   $todayWithdraw=(float)dw_scalar($conn,"SELECT COALESCE(SUM(amount),0) FROM withdraw_requests WHERE status='approved' AND created_at>=CURDATE()");
   $pendingRecharge=(int)dw_scalar($conn,"SELECT COUNT(*) FROM recharge_orders WHERE status IN ('Wait','PendingReview')");
   $betVolume=(float)dw_scalar($conn,"SELECT COALESCE(SUM(real_amount+fee),0) FROM lottery_bets WHERE created_at>=CURDATE()");
   $winPaid=(float)dw_scalar($conn,"SELECT COALESCE(SUM(GREATEST(win_lose_amount,0)),0) FROM lottery_bets WHERE created_at>=CURDATE() AND state=1");
   $todayProfit=$betVolume-$winPaid;
   ?>
   <div class="dashboard-heading"><div><h2>Dashboard Overview</h2><p>Statistics for <?=dw_h(date('F j, Y'))?></p></div><span class="live-pill">● Live</span></div>
   <h3 class="section-title">🚀 Quick Actions</h3>
   <div class="quick-actions">
    <a class="quick-card purple" href="?page=settings"><span>🛠</span><strong>Site Maintenance</strong></a>
    <a class="quick-card green" href="?page=gifts"><span>🎁</span><strong>Create Gift Code</strong></a>
    <a class="quick-card red" href="?page=risk"><span>⊘</span><strong>Check Same IP</strong></a>
    <a class="quick-card orange" href="?page=agents"><span>₹</span><strong>Manage Salary</strong></a>
   </div>
   <h3 class="section-title">📊 Live Statistics</h3>
   <div class="grid kpis dashboard-kpis">
    <article class="kpi color-cyan"><div class="label">Total Users</div><div class="value"><?=number_format($totalUsers)?></div><a class="sub" href="?page=users">View All Users</a></article>
    <article class="kpi color-purple"><div class="label">User Wallet</div><div class="value">₹<?=dw_money($userWallet)?></div><a class="sub" href="?page=ledger">Check Balances</a></article>
    <article class="kpi color-green"><div class="label">Today's Recharge</div><div class="value">₹<?=dw_money($todayRecharge)?></div><a class="sub" href="?page=recharges">View Report</a></article>
    <article class="kpi color-red"><div class="label">Today's Withdrawal</div><div class="value">₹<?=dw_money($todayWithdraw)?></div><a class="sub" href="?page=withdrawals">View Report</a></article>
    <article class="kpi color-orange"><div class="label">Pending Recharge</div><div class="value"><?=number_format($pendingRecharge)?></div><a class="sub" href="?page=recharges&status=Wait">Approve Now</a></article>
    <article class="kpi color-dark"><div class="label">Today's Profit</div><div class="value">₹<?=dw_money($todayProfit)?></div><span class="sub">Bets minus paid wins</span></article>
   </div>
   <div class="split">
    <section class="panel"><div class="panel-head"><h2>Latest deposit queue</h2><a class="btn sm" href="?page=recharges">Open queue</a></div><div class="table-wrap"><table class="table"><thead><tr><th>Order</th><th>User</th><th>Amount</th><th>Status</th></tr></thead><tbody><?php foreach(dw_rows($conn,"SELECT r.*,u.username FROM recharge_orders r LEFT JOIN users u ON u.id=r.user_id ORDER BY r.id DESC LIMIT 8") as $r):?><tr><td class="mono"><?=dw_h($r['order_no'])?></td><td><?=dw_h($r['username'])?></td><td>₹<?=dw_money((float)$r['amount']+(float)$r['gift_amount'])?></td><td><?=dw_badge($r['status'])?></td></tr><?php endforeach;?></tbody></table></div></section>
    <section class="panel"><div class="panel-head"><h2>Latest withdrawal queue</h2><a class="btn sm" href="?page=withdrawals">Open queue</a></div><div class="table-wrap"><table class="table"><thead><tr><th>Order</th><th>User</th><th>Amount</th><th>Status</th></tr></thead><tbody><?php foreach(dw_rows($conn,"SELECT w.*,u.username FROM withdraw_requests w LEFT JOIN users u ON u.id=w.user_id ORDER BY w.id DESC LIMIT 8") as $r):?><tr><td class="mono"><?=dw_h($r['order_no']?:$r['id'])?></td><td><?=dw_h($r['username'])?></td><td>₹<?=dw_money($r['amount'])?></td><td><?=dw_badge($r['status'])?></td></tr><?php endforeach;?></tbody></table></div></section>
   </div>
   <section class="panel"><div class="panel-head"><h2>Operations coverage</h2><span class="badge">120+ operational controls</span></div><div class="panel-body"><ul class="feature-list small"><li>Secure role-based admins</li><li>Admin login rate limiting</li><li>Complete audit trail</li><li>User search & status</li><li>Balance credit/debit</li><li>User session revoke</li><li>Password/PIN reset</li><li>VIP and agent flags</li><li>Deposit approve/reject</li><li>Deposit wager locking</li><li>Withdrawal reservation</li><li>Reject auto-refund</li><li>Turnover progress</li><li>Manual turnover override</li><li>Detailed balance ledger</li><li>CSV exports</li><li>Game availability</li><li>Game maintenance</li><li>RTP and sorting</li><li>WinGo force mode</li><li>Manual issue results</li><li>Pending bet settlement</li><li>Payout and fee rules</li><li>Gift code creation</li><li>Gift claim history</li><li>Payment method controls</li><li>Banner management</li><li>Notification management</li><li>VIP level rules</li><li>Activity tasks</li><li>Recharge wheel controls</li><li>Invite wheel controls</li><li>Support replies</li><li>Agent hierarchy</li><li>Risk flags</li><li>Feature switches</li><li>Withdrawal limits</li><li>System health checks</li><li>Official provider launch adapters</li><li>Signed provider wallet callbacks</li><li>Idempotent provider transactions</li><li>Recursive team analytics</li><li>Three-level bet commission posting</li><li>Commission claim settlement</li><li>Support ticket lifecycle</li><li>Local support uploads</li><li>5D/K3/TRX issue health</li><li>Live admin round timers</li><li>Provider secret environment isolation</li><li>Admin credential recovery migration</li></ul></div></section>

 <?php elseif($page==='users'):
   $q=trim((string)($_GET['q']??''));$status=(string)($_GET['status']??'all');$p=max(1,(int)($_GET['p']??1));$size=30;$off=($p-1)*$size;$where=["u.role='user'"];if($q!==''){$e=$conn->real_escape_string($q);$where[]="(u.username LIKE '%$e%' OR u.mobile LIKE '%$e%' OR u.nickname LIKE '%$e%' OR u.id='".(int)$q."')";}if($status==='active')$where[]='u.status=1';if($status==='suspended')$where[]='u.status=0';$ws=implode(' AND ',$where);$total=(int)dw_scalar($conn,"SELECT COUNT(*) FROM users u WHERE $ws");$users=dw_rows($conn,"SELECT u.*,COALESCE(w.locked,0) locked,COALESCE(w.need,0) need FROM users u LEFT JOIN (SELECT user_id,SUM(locked_amount) locked,SUM(GREATEST(required_turnover-completed_turnover,0)) need FROM wager_requirements WHERE status='active' GROUP BY user_id) w ON w.user_id=u.id WHERE $ws ORDER BY u.id DESC LIMIT $size OFFSET $off");?>
   <div class="split">
    <section class="panel"><div class="panel-head"><h2>Create Demo User</h2><span class="badge">Separate demo flag</span></div><div class="panel-body"><form method="post" class="form-grid"><?php dw_meta('users')?><input type="hidden" name="action" value="demo_user_create"><div class="field"><label>Username (blank = auto)</label><input class="input" name="username"></div><div class="field"><label>Mobile (optional)</label><input class="input" name="mobile"></div><div class="field"><label>Display name</label><input class="input" name="nickname" value="Demo User"></div><div class="field"><label>Password (8+ chars)</label><input class="input" type="password" minlength="8" name="password" required></div><div class="field"><label>Opening balance</label><input class="input" type="number" step=".01" min="0" name="opening_balance" value="0"></div><div class="field"><label>&nbsp;</label><button class="btn primary">Add Demo User</button></div></form></div></section>
    <section class="panel"><div class="panel-head"><h2>User Status</h2></div><div class="panel-body grid mini-kpis"><article class="mini-kpi"><span>Active</span><strong><?=number_format((int)dw_scalar($conn,"SELECT COUNT(*) FROM users WHERE role='user' AND status=1"))?></strong></article><article class="mini-kpi"><span>Banned</span><strong><?=number_format((int)dw_scalar($conn,"SELECT COUNT(*) FROM users WHERE role='user' AND status=0"))?></strong></article><article class="mini-kpi"><span>Demo</span><strong><?=number_format((int)dw_scalar($conn,"SELECT COUNT(*) FROM users WHERE role='user' AND is_demo=1"))?></strong></article></div></section>
   </div>
   <section class="panel"><div class="panel-head"><h2>User directory <span class="muted">(<?=number_format($total)?>)</span></h2><a class="btn sm" href="?page=users&export=users">Export CSV</a></div><div class="panel-body"><form class="toolbar"><input type="hidden" name="page" value="users"><div class="field"><label>Search ID, mobile, username</label><input class="input" name="q" value="<?=dw_h($q)?>"></div><div class="field"><label>Status</label><select name="status"><option value="all">All</option><option value="active" <?=$status==='active'?'selected':''?>>Active</option><option value="suspended" <?=$status==='suspended'?'selected':''?>>Suspended</option></select></div><button class="btn primary">Filter</button></form></div>
   <div class="table-wrap"><table class="table"><thead><tr><th>User</th><th>Contact</th><th>Balance</th><th>Turnover lock</th><th>VIP / Agent</th><th>Status</th><th>Joined</th><th>Controls</th></tr></thead><tbody>
   <?php foreach($users as $u):$withdrawable=max(0,(float)$u['balance']-(float)$u['locked']);?><tr><td><strong>#<?=dw_h($u['id'])?> · <?=dw_h($u['nickname'])?></strong><div class="small mono"><?=dw_h($u['username'])?></div><?php if(!empty($u['is_demo'])):?><?=dw_badge('Demo')?><?php endif;?></td><td><?=dw_h($u['mobile']?:$u['email'])?><div class="small muted">IP <?=dw_h($u['ip_last'])?></div></td><td><strong>₹<?=dw_money($u['balance'])?></strong><div class="small muted">Withdrawable ₹<?=dw_money($withdrawable)?></div></td><td>₹<?=dw_money($u['locked'])?><div class="small muted">Need bet ₹<?=dw_money($u['need'])?></div></td><td>VIP <?=dw_h($u['vip_level'])?> · <?=$u['is_agent']?'Agent':'Member'?></td><td><?=dw_badge((int)$u['status']===1?'Active':'Suspended')?></td><td class="small"><?=dw_h($u['created_at'])?></td><td><div class="actions">
    <form method="post" class="inline"><?php dw_meta('users')?><input type="hidden" name="action" value="user_status"><input type="hidden" name="id" value="<?=dw_h($u['id'])?>"><input type="hidden" name="status" value="<?=(int)$u['status']===1?0:1?>"><button class="btn sm <?=(int)$u['status']===1?'danger':'primary'?>" data-confirm="Change this user status?"><?=(int)$u['status']===1?'Suspend':'Activate'?></button></form>
    <details class="action-box"><summary class="btn sm">Balance</summary><form method="post" class="popover"><?php dw_meta('users')?><input type="hidden" name="action" value="user_adjust_balance"><input type="hidden" name="id" value="<?=dw_h($u['id'])?>"><div class="form-grid"><div class="field"><label>Direction</label><select name="direction"><option value="credit">Credit</option><option value="debit">Debit</option></select></div><div class="field"><label>Amount</label><input class="input" type="number" step=".01" min=".01" name="amount" required></div><div class="field wide"><label>Reason</label><input class="input" name="reason" required></div><div class="field"><label>Credit wager multiplier</label><input class="input" type="number" step=".1" min="0" name="turnover_multiplier" value="0"></div><div><button class="btn primary" data-confirm="Post this wallet adjustment?">Post ledger entry</button></div></div></form></details>
    <details class="action-box"><summary class="btn sm">Security</summary><div class="popover"><?php foreach([['user_reset_session','Revoke all sessions'],['user_reset_withdraw_pin','Clear withdrawal PIN']] as $a):?><form method="post" style="margin-bottom:8px"><?php dw_meta('users')?><input type="hidden" name="action" value="<?=$a[0]?>"><input type="hidden" name="id" value="<?=dw_h($u['id'])?>"><button class="btn warn" data-confirm="<?=$a[1]?>?"><?=$a[1]?></button></form><?php endforeach;?><form method="post"><?php dw_meta('users')?><input type="hidden" name="action" value="user_reset_password"><input type="hidden" name="id" value="<?=dw_h($u['id'])?>"><div class="field"><label>Temporary password</label><input class="input" type="password" name="password" minlength="8" required></div><button class="btn danger" data-confirm="Reset password and revoke sessions?">Reset password</button></form></div></details>
    <details class="action-box"><summary class="btn sm">Profile</summary><form method="post" class="popover"><?php dw_meta('users')?><input type="hidden" name="action" value="user_profile_flags"><input type="hidden" name="id" value="<?=dw_h($u['id'])?>"><div class="field"><label>VIP level</label><input class="input" type="number" name="vip_level" value="<?=dw_h($u['vip_level'])?>" min="0"></div><label class="check"><input type="checkbox" name="is_agent" <?=$u['is_agent']?'checked':''?>> Agent account</label><button class="btn primary">Save profile</button></form></details>
   </div></td></tr><?php endforeach;?></tbody></table></div><?php dw_pages($total,$size,$p,['page'=>'users','q'=>$q,'status'=>$status]);?></section>

 <?php elseif($page==='recharges'):
   $status=(string)($_GET['status']??'all');$q=trim((string)($_GET['q']??''));$p=max(1,(int)($_GET['p']??1));$size=30;$off=($p-1)*$size;$where=['1=1'];if(in_array($status,['Wait','PendingReview','Payed','Cancel'],true))$where[]="r.status='".$conn->real_escape_string($status)."'";if($q!==''){$e=$conn->real_escape_string($q);$where[]="(r.order_no LIKE '%$e%' OR r.utr LIKE '%$e%' OR u.username LIKE '%$e%')";}$ws=implode(' AND ',$where);$total=(int)dw_scalar($conn,"SELECT COUNT(*) FROM recharge_orders r LEFT JOIN users u ON u.id=r.user_id WHERE $ws");$rows=dw_rows($conn,"SELECT r.*,u.username,u.balance FROM recharge_orders r LEFT JOIN users u ON u.id=r.user_id WHERE $ws ORDER BY r.id DESC LIMIT $size OFFSET $off");?>
   <section class="panel"><div class="panel-head"><h2>Deposit orders</h2><a class="btn sm" href="?page=recharges&export=recharges">Export CSV</a></div><div class="panel-body"><form class="toolbar"><input type="hidden" name="page" value="recharges"><div class="field"><label>Order / UTR / user</label><input class="input" name="q" value="<?=dw_h($q)?>"></div><div class="field"><label>Status</label><select name="status"><option value="all">All</option><?php foreach(['Wait','PendingReview','Payed','Cancel'] as $s):?><option <?=$status===$s?'selected':''?>><?=$s?></option><?php endforeach;?></select></div><button class="btn primary">Filter</button></form></div><div class="table-wrap"><table class="table"><thead><tr><th>Order</th><th>User</th><th>Principal + gift</th><th>Channel</th><th>UTR / proof</th><th>Status</th><th>Time</th><th>Decision</th></tr></thead><tbody>
   <?php foreach($rows as $r):?><tr><td class="mono"><?=dw_h($r['order_no'])?></td><td>#<?=dw_h($r['user_id'])?> <?=dw_h($r['username'])?><div class="small muted">Balance ₹<?=dw_money($r['balance'])?></div></td><td><strong>₹<?=dw_money($r['amount'])?></strong> + ₹<?=dw_money($r['gift_amount'])?><div class="small muted">1× principal turnover on approval</div></td><td><?=dw_h($r['channel_name'])?><div class="small"><?=dw_h($r['recharge_type'])?></div></td><td class="mono"><?=dw_h($r['utr']?:'—')?><?php if(!empty($r['payment_proof'])):?><div><a href="<?=dw_h($r['payment_proof'])?>" target="_blank" rel="noopener">Open proof</a></div><?php endif;?></td><td><?=dw_badge($r['status'])?></td><td class="small"><?=dw_h($r['created_at'])?></td><td><?php if(in_array($r['status'],['Wait','PendingReview'],true)):?><details class="action-box"><summary class="btn sm primary">Review</summary><form method="post" class="popover"><?php dw_meta('recharges')?><input type="hidden" name="action" value="recharge_process"><input type="hidden" name="id" value="<?=dw_h($r['id'])?>"><div class="field"><label>Admin note</label><textarea name="admin_note"></textarea></div><div class="actions"><button class="btn primary" name="decision" value="approve" data-confirm="Approve and credit this deposit with turnover lock?">Approve</button><button class="btn danger" name="decision" value="reject" data-confirm="Reject this deposit?">Reject</button></div></form></details><?php else:?><span class="small muted"><?=dw_h($r['admin_note'])?></span><?php endif;?></td></tr><?php endforeach;?></tbody></table></div><?php dw_pages($total,$size,$p,['page'=>'recharges','q'=>$q,'status'=>$status]);?></section>

 <?php elseif($page==='withdrawals'):
   $status=(string)($_GET['status']??'all');$method=trim((string)($_GET['method']??''));$p=max(1,(int)($_GET['p']??1));$size=30;$off=($p-1)*$size;$filters=['1=1'];if(in_array($status,['pending','approved','rejected'],true))$filters[]="w.status='".$conn->real_escape_string($status)."'";if($method!=='')$filters[]="w.method LIKE '%".$conn->real_escape_string($method)."%'";$where='WHERE '.implode(' AND ',$filters);$total=(int)dw_scalar($conn,"SELECT COUNT(*) FROM withdraw_requests w $where");$rows=dw_rows($conn,"SELECT w.*,u.username,u.balance FROM withdraw_requests w LEFT JOIN users u ON u.id=w.user_id $where ORDER BY w.id DESC LIMIT $size OFFSET $off");?>
   <section class="panel"><div class="panel-head"><h2>Withdrawal orders</h2><a class="btn sm" href="?page=withdrawals&export=withdrawals">Export CSV</a></div><div class="panel-body"><form class="toolbar"><input type="hidden" name="page" value="withdrawals"><div class="field"><label>Status</label><select name="status"><option value="all">All</option><?php foreach(['pending','approved','rejected'] as $s):?><option value="<?=dw_h($s)?>" <?=$status===$s?'selected':''?>><?=ucfirst($s)?></option><?php endforeach;?></select></div><div class="field"><label>Method</label><input class="input" name="method" value="<?=dw_h($method)?>" placeholder="UPI / USDT / BankCard"></div><button class="btn primary">Filter</button></form></div><div class="table-wrap"><table class="table"><thead><tr><th>Order</th><th>User</th><th>Amount</th><th>Account</th><th>Reservation</th><th>Status</th><th>Time</th><th>Decision</th></tr></thead><tbody>
   <?php foreach($rows as $r):$sum=wallet_wager_summary($conn,(int)$r['user_id'],(float)$r['balance']);?><tr><td class="mono"><?=dw_h($r['order_no']?:$r['id'])?></td><td>#<?=dw_h($r['user_id'])?> <?=dw_h($r['username'])?><div class="small muted">Now ₹<?=dw_money($r['balance'])?></div></td><td><strong>₹<?=dw_money($r['amount'])?></strong><div class="small muted">Before ₹<?=dw_money($r['balance_before'])?> → after ₹<?=dw_money($r['balance_after'])?></div></td><td><?=dw_wallet_display($r)?><div class="small"><?=dw_h($r['method'])?></div></td><td><?=dw_badge((int)$r['is_reserved']===1?'Reserved':'Legacy')?><div class="small muted">Need bet ₹<?=dw_money($sum['needBetAmount'])?></div></td><td><?=dw_badge($r['status'])?></td><td class="small"><?=dw_h($r['created_at'])?></td><td><?php if($r['status']==='pending'):?><details class="action-box"><summary class="btn sm primary">Review</summary><form method="post" class="popover"><?php dw_meta('withdrawals')?><input type="hidden" name="action" value="withdraw_process"><input type="hidden" name="id" value="<?=dw_h($r['id'])?>"><div class="field"><label>Bank/admin note</label><textarea name="admin_note" required></textarea></div><div class="actions"><button class="btn primary" name="decision" value="approved" data-confirm="Mark this reserved withdrawal approved?">Withdraw Sent</button><button class="btn danger" name="decision" value="rejected" data-confirm="Reject and return reserved amount to the user?">Withdraw Reject + Refund</button></div></form></details><?php else:?><span class="small muted"><?=dw_h($r['admin_note'])?></span><?php endif;?></td></tr><?php endforeach;?></tbody></table></div><?php dw_pages($total,$size,$p,['page'=>'withdrawals','status'=>$status,'method'=>$method]);?></section>

 <?php elseif($page==='ledger'):
   $type=trim((string)($_GET['type']??''));$q=trim((string)($_GET['q']??''));$p=max(1,(int)($_GET['p']??1));$size=40;$off=($p-1)*$size;$where=['1=1'];if($type!=='')$where[]="f.type='".$conn->real_escape_string($type)."'";if($q!==''){$e=$conn->real_escape_string($q);$where[]="(f.order_no LIKE '%$e%' OR f.record_no LIKE '%$e%' OR u.username LIKE '%$e%')";}$ws=implode(' AND ',$where);$total=(int)dw_scalar($conn,"SELECT COUNT(*) FROM financial_records f LEFT JOIN users u ON u.id=f.user_id WHERE $ws");$rows=dw_rows($conn,"SELECT f.*,u.username FROM financial_records f LEFT JOIN users u ON u.id=f.user_id WHERE $ws ORDER BY f.id DESC LIMIT $size OFFSET $off");$types=dw_rows($conn,'SELECT DISTINCT type FROM financial_records ORDER BY type');?>
   <section class="panel"><div class="panel-head"><h2>Detailed wallet ledger</h2><a class="btn sm" href="?page=ledger&export=ledger">Export CSV</a></div><div class="panel-body"><form class="toolbar"><input type="hidden" name="page" value="ledger"><div class="field"><label>Order / record / user</label><input class="input" name="q" value="<?=dw_h($q)?>"></div><div class="field"><label>Transaction type</label><select name="type"><option value="">All types</option><?php foreach($types as $t):?><option <?=$type===$t['type']?'selected':''?>><?=dw_h($t['type'])?></option><?php endforeach;?></select></div><button class="btn primary">Filter</button></form></div><div class="table-wrap"><table class="table"><thead><tr><th>Record / order</th><th>User</th><th>Type</th><th>Change</th><th>Balance before → after</th><th>Description</th><th>Time</th></tr></thead><tbody>
   <?php foreach($rows as $r):?><tr><td class="mono"><?=dw_h($r['record_no'])?><div><?=dw_h($r['order_no'])?></div></td><td>#<?=dw_h($r['user_id'])?> <?=dw_h($r['username'])?></td><td><?=dw_badge($r['type'])?><div class="small"><?=dw_h($r['sub_type'])?></div></td><td class="amount <?=(float)$r['amount']>=0?'plus':'minus'?>"><?=(float)$r['amount']>=0?'+':''?>₹<?=dw_money($r['amount'])?></td><td><strong>₹<?=dw_money($r['balance_before'])?> → ₹<?=dw_money($r['back_amount'])?></strong></td><td><?=dw_h($r['description']?:wallet_type_label($r['type']))?><div class="small muted"><?=dw_h($r['remark'])?></div></td><td class="small"><?=dw_h($r['created_at'])?></td></tr><?php endforeach;?></tbody></table></div><?php dw_pages($total,$size,$p,['page'=>'ledger','q'=>$q,'type'=>$type]);?></section>

 <?php elseif($page==='wagers'):
   $status=(string)($_GET['status']??'active');$where=in_array($status,['active','completed','cancelled'],true)?"WHERE w.status='".$conn->real_escape_string($status)."'":'';$rows=dw_rows($conn,"SELECT w.*,u.username,u.balance FROM wager_requirements w LEFT JOIN users u ON u.id=w.user_id $where ORDER BY w.id DESC LIMIT 200");?>
   <div class="grid kpis"><article class="kpi"><div class="label">Active locked principal</div><div class="value">₹<?=dw_money(dw_scalar($conn,"SELECT COALESCE(SUM(locked_amount),0) FROM wager_requirements WHERE status='active'"))?></div></article><article class="kpi"><div class="label">Remaining turnover</div><div class="value">₹<?=dw_money(dw_scalar($conn,"SELECT COALESCE(SUM(GREATEST(required_turnover-completed_turnover,0)),0) FROM wager_requirements WHERE status='active'"))?></div></article><article class="kpi"><div class="label">Completed requirements</div><div class="value"><?=number_format((int)dw_scalar($conn,"SELECT COUNT(*) FROM wager_requirements WHERE status='completed'"))?></div></article><article class="kpi"><div class="label">Bet events</div><div class="value"><?=number_format((int)dw_scalar($conn,'SELECT COUNT(*) FROM wager_requirement_events'))?></div></article></div>
   <section class="panel"><div class="panel-head"><h2>Deposit and bonus turnover</h2></div><div class="panel-body"><form class="toolbar"><input type="hidden" name="page" value="wagers"><div class="field"><label>Status</label><select name="status"><?php foreach(['active','completed','cancelled','all'] as $s):?><option value="<?=dw_h($s)?>" <?=$status===$s?'selected':''?>><?=ucfirst($s)?></option><?php endforeach;?></select></div><button class="btn primary">Filter</button></form></div><div class="table-wrap"><table class="table"><thead><tr><th>Source</th><th>User</th><th>Locked</th><th>Turnover progress</th><th>Status / dates</th><th>Admin override</th></tr></thead><tbody>
   <?php foreach($rows as $r):$pct=(float)$r['required_turnover']>0?min(100,(float)$r['completed_turnover']/(float)$r['required_turnover']*100):100;?><tr><td>#<?=dw_h($r['id'])?> <?=dw_badge($r['source_type'])?><div class="mono small"><?=dw_h($r['source_order_no'])?></div></td><td>#<?=dw_h($r['user_id'])?> <?=dw_h($r['username'])?><div class="small">Balance ₹<?=dw_money($r['balance'])?></div></td><td>₹<?=dw_money($r['locked_amount'])?></td><td><strong>₹<?=dw_money($r['completed_turnover'])?> / ₹<?=dw_money($r['required_turnover'])?></strong><div class="progress"><span style="width:<?=round($pct)?>%"></span></div><div class="small muted"><?=round($pct,1)?>%</div></td><td><?=dw_badge($r['status'])?><div class="small muted"><?=dw_h($r['created_at'])?></div></td><td><?php if($r['status']==='active'):?><details class="action-box"><summary class="btn sm warn">Override</summary><form method="post" class="popover"><?php dw_meta('wagers')?><input type="hidden" name="action" value="wager_override"><input type="hidden" name="id" value="<?=dw_h($r['id'])?>"><div class="field"><label>Mandatory reason</label><textarea name="reason" required></textarea></div><div class="actions"><button class="btn warn" name="decision" value="complete" data-confirm="Mark turnover complete without a bet?">Complete</button><button class="btn danger" name="decision" value="cancel" data-confirm="Cancel and unlock this requirement?">Cancel / unlock</button></div></form></details><?php endif;?></td></tr><?php endforeach;?></tbody></table></div></section>

 <?php elseif($page==='games'):
   $rows=dw_rows($conn,'SELECT * FROM games ORDER BY category_code,sort DESC,id DESC LIMIT 500');?>
   <section class="panel"><div class="panel-head"><h2>Game availability, maintenance, RTP and order</h2><input class="input" style="max-width:260px" placeholder="Filter visible games…" data-filter-table="#games-table"></div><div class="table-wrap"><table class="table" id="games-table"><thead><tr><th>Game</th><th>Category / vendor</th><th>Image</th><th>Controls</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><strong><?=dw_h($r['name'])?></strong><div class="mono small"><?=dw_h($r['game_code'])?></div></td><td><?=dw_h($r['category_code'])?><div class="small"><?=dw_h($r['vendor_code'])?></div></td><td><?php if($r['img']):?><img src="<?=dw_h($r['img'])?>" alt="" width="42" height="42" loading="lazy"><?php endif;?></td><td><form method="post" class="toolbar"><?php dw_meta('games')?><input type="hidden" name="action" value="game_update"><input type="hidden" name="id" value="<?=dw_h($r['id'])?>"><label class="check"><input type="checkbox" name="status" <?=$r['status']?'checked':''?>> Enabled</label><label class="check"><input type="checkbox" name="is_maintenance" <?=$r['is_maintenance']?'checked':''?>> Maintenance</label><div class="field"><label>RTP %</label><input class="input" style="width:85px" type="number" step=".01" name="rtp" value="<?=dw_h($r['rtp'])?>"></div><div class="field"><label>Sort</label><input class="input" style="width:80px" type="number" name="sort" value="<?=dw_h($r['sort'])?>"></div><button class="btn sm primary">Save</button></form></td></tr><?php endforeach;?></tbody></table></div></section>

 <?php elseif($page==='providers'):
   $providers=dw_rows($conn,'SELECT * FROM third_party_providers ORDER BY display_name,vendor_code');?>
   <div class="notice"><strong>Official integration only.</strong> Merchant secrets stay in server environment variables; this panel stores only the environment-key name. Disabled providers open a local status page instead of a broken/unsafe remote URL.</div>
   <section class="panel">
    <div class="panel-head"><h2>JILI, JDB, Aviator and other providers</h2><span class="badge"><?=count($providers)?> adapters</span></div>
    <div class="panel-body provider-list">
     <?php foreach($providers as $r):$secretKey=(string)$r['secret_env_key'];$callbackKey=(string)$r['callback_secret_env_key'];$secretReady=$secretKey!=='' && getenv($secretKey)!==false && (string)getenv($secretKey)!=='';$callbackReady=($callbackKey!=='' && getenv($callbackKey)!==false && (string)getenv($callbackKey)!=='') || ($callbackKey==='' && $secretReady);?>
      <form method="post" class="provider-card"><?php dw_meta('providers')?>
       <input type="hidden" name="action" value="provider_save"><input type="hidden" name="id" value="<?=dw_h($r['id'])?>">
       <div class="form-grid">
        <div class="field"><label>Vendor code</label><input class="input mono" name="vendor_code" value="<?=dw_h($r['vendor_code'])?>" required></div>
        <div class="field"><label>Display name</label><input class="input" name="display_name" value="<?=dw_h($r['display_name'])?>" required></div>
        <div class="field"><label>Mode</label><select name="integration_mode"><?php foreach(['disabled','demo','official'] as $mode):?><option <?=$r['integration_mode']===$mode?'selected':''?>><?=$mode?></option><?php endforeach;?></select></div>
        <div class="field"><label>Merchant ID</label><input class="input" name="merchant_id" value="<?=dw_h($r['merchant_id'])?>"></div>
        <div class="field wide"><label>HTTPS launch URL template</label><input class="input" name="launch_url_template" value="<?=dw_h($r['launch_url_template'])?>" placeholder="https://provider.example/launch?game={gameCode}&token={token}"></div>
        <div class="field"><label>Allowed host</label><input class="input" name="allowed_host" value="<?=dw_h($r['allowed_host'])?>" placeholder="provider.example"></div>
        <div class="field"><label>Secret environment key</label><input class="input mono" name="secret_env_key" value="<?=dw_h($secretKey)?>" placeholder="DW_JILI_SECRET"></div>
        <div class="field"><label>Callback secret env key (optional)</label><input class="input mono" name="callback_secret_env_key" value="<?=dw_h($callbackKey)?>" placeholder="DW_JILI_CALLBACK_SECRET"></div>
       </div>
       <div class="provider-footer"><label class="check"><input type="checkbox" name="status" <?=$r['status']?'checked':''?>> Enabled</label><span><?=dw_badge($secretReady?'Launch secret ready':($r['integration_mode']==='official'?'Launch secret missing':'Not required'))?></span><span><?=dw_badge($callbackReady?'Callback secret ready':($r['integration_mode']==='official'?'Callback secret missing':'Not required'))?></span><span class="small muted">Secret values stay in the server environment.</span><button class="btn primary" data-confirm="Save this provider adapter?">Save provider</button></div>
      </form>
     <?php endforeach;?>
    </div>
   </section>

 <?php elseif($page==='wingo'):
   $controlGames=['WinGo_30S','WinGo_1M','WinGo_3M','WinGo_5M','K3_1M','K3_3M','K3_5M','K3_10M','D5_1M','D5_3M','D5_5M','D5_10M','TrxWinGo_1M','TrxWinGo_3M','TrxWinGo_5M','TrxWinGo_10M'];
   $gameControl=(string)($_GET['game']??'WinGo_30S');if(!in_array($gameControl,$controlGames,true))$gameControl='WinGo_30S';
   $intervalControl=le_game_interval($gameControl);$issueData=lottery_issue($gameControl);$issueControl=(string)$issueData['issueNumber'];$remainingControl=(int)$issueData['countdown'];
   $gameEsc=$conn->real_escape_string($gameControl);$issueEsc=$conn->real_escape_string($issueControl);
   $currentManual=(string)dw_scalar($conn,"SELECT premium FROM lottery_results WHERE game_code='$gameEsc' AND issue_number='$issueEsc' LIMIT 1",'NOT SET');
   $issueBetTotal=(float)dw_scalar($conn,"SELECT COALESCE(SUM(real_amount+fee),0) FROM lottery_bets WHERE game_code='$gameEsc' AND issue_number='$issueEsc'");
   $manualRows=dw_rows($conn,"SELECT bet_content,COUNT(*) bet_count,COUNT(DISTINCT user_id) users,COALESCE(SUM(real_amount+fee),0) pay FROM lottery_bets WHERE game_code='$gameEsc' AND issue_number='$issueEsc' GROUP BY bet_content ORDER BY pay DESC");
   $settingsRows=dw_rows($conn,'SELECT * FROM lottery_game_settings ORDER BY game_code');$results=dw_rows($conn,"SELECT * FROM lottery_results WHERE game_code='$gameEsc' ORDER BY id DESC LIMIT 40");$bets=dw_rows($conn,"SELECT b.*,u.username FROM lottery_bets b LEFT JOIN users u ON u.id=b.user_id WHERE b.game_code='$gameEsc' ORDER BY b.id DESC LIMIT 60");?>
   <section class="panel lottery-control" data-lottery-control data-game="<?=dw_h($gameControl)?>" data-interval="<?=dw_h($intervalControl)?>" data-remaining="<?=dw_h($remainingControl)?>">
    <div class="panel-head"><div><h2><?=dw_h(game_name_from_code($gameControl))?> Control</h2><span class="small muted">Live issue timer and manual result manager</span></div><form method="get" class="toolbar"><input type="hidden" name="page" value="wingo"><select name="game" onchange="this.form.submit()"><?php foreach($controlGames as $code):?><option value="<?=dw_h($code)?>" <?=$gameControl===$code?'selected':''?>><?=dw_h(game_name_from_code($code))?></option><?php endforeach;?></select></form></div>
    <div class="panel-body">
     <div class="timer-strip"><div><span>TIME LEFT</span><strong data-control-timer><?=sprintf('%02d:%02d',intdiv($remainingControl,60),$remainingControl%60)?></strong></div><div><span>CURRENT ISSUE</span><strong class="mono" data-control-issue><?=dw_h($issueControl)?></strong></div><div><span>NEXT RESULT</span><strong data-control-result><?=dw_h($currentManual?:'NOT SET')?></strong></div></div>
     <form method="post" class="result-setter"><?php dw_meta('wingo')?><input type="hidden" name="action" value="lottery_result_save"><input type="hidden" name="game_code" value="<?=dw_h($gameControl)?>"><input type="hidden" name="issue_number" value="<?=dw_h($issueControl)?>" data-control-issue-input><div class="field"><label>Result (WinGo/TRX: 0-9 · K3: 3 dice · 5D: 5 digits)</label><input class="input result-input" name="premium" required placeholder="Enter result"></div><button class="btn primary" data-confirm="Set and settle this issue result?">SET</button></form>
     <form method="post" class="result-unset"><?php dw_meta('wingo')?><input type="hidden" name="action" value="lottery_result_unset"><input type="hidden" name="game_code" value="<?=dw_h($gameControl)?>"><input type="hidden" name="issue_number" value="<?=dw_h($issueControl)?>" data-control-issue-input><button class="btn danger" data-confirm="Remove this manual result if no bet is settled?">UNSET</button></form>
    </div>
   </section>
   <div class="total-bets"><span>TOTAL BETS · <?=dw_h($issueControl)?></span><strong>₹<?=dw_money($issueBetTotal)?></strong></div>
   <section class="panel"><div class="panel-head"><h2>Manual History</h2><span class="badge"><?=count($manualRows)?> selections</span></div><div class="table-wrap"><table class="table compact"><thead><tr><th>Result / selection</th><th>Bets</th><th>Users</th><th>Pay</th></tr></thead><tbody><?php if(!$manualRows):?><tr><td colspan="4" class="empty">No bets in this live issue yet.</td></tr><?php else:foreach($manualRows as $r):?><tr><td><strong><?=dw_h($r['bet_content'])?></strong></td><td><?=number_format((int)$r['bet_count'])?></td><td><?=number_format((int)$r['users'])?></td><td>₹<?=dw_money($r['pay'])?></td></tr><?php endforeach;endif;?></tbody></table></div></section>
   <div class="split"><section class="panel"><div class="panel-head"><h2>WinGo / lottery engine settings</h2></div><div class="panel-body"><form method="post" class="form-grid"><?php dw_meta('wingo')?><input type="hidden" name="action" value="lottery_setting_save"><div class="field"><label>Game code (* = default)</label><input class="input" name="game_code" value="*"></div><div class="field"><label>Force mode</label><select name="force_mode"><option>auto</option><option>win</option><option>lose</option></select></div><div class="field"><label>Forced result (blank=random)</label><input class="input" name="force_result"></div><div class="field"><label>Win rate %</label><input class="input" type="number" step=".01" name="win_rate" value="45"></div><div class="field"><label>Fee %</label><input class="input" type="number" step=".01" name="fee_percent" value="0"></div><div class="field"><label>Number payout</label><input class="input" type="number" step=".01" name="payout_number" value="9"></div><div class="field"><label>Color payout</label><input class="input" type="number" step=".01" name="payout_color" value="2"></div><div class="field"><label>Violet payout</label><input class="input" type="number" step=".01" name="payout_violet" value="4.5"></div><div class="field"><label>Big/small payout</label><input class="input" type="number" step=".01" name="payout_bigsmall" value="2"></div><div class="field"><label>K3 payout</label><input class="input" type="number" step=".01" name="payout_k3" value="2"></div><div class="field"><label>5D payout</label><input class="input" type="number" step=".01" name="payout_5d" value="9.5"></div><div class="field"><label>Moto payout</label><input class="input" type="number" step=".01" name="payout_moto" value="9.5"></div><label class="check wide"><input type="checkbox" name="immediate_settle"<?=le_instant_result()?' checked':''?>> Immediate settlement when eligible</label><button class="btn primary">Save engine setting</button></form></div></section>
   <section class="panel"><div class="panel-head"><h2>Manual issue result</h2></div><div class="panel-body"><form method="post" class="form-grid"><?php dw_meta('wingo')?><input type="hidden" name="action" value="lottery_result_save"><div class="field"><label>Game code</label><input class="input" name="game_code" value="<?=dw_h($gameControl)?>" required></div><div class="field"><label>Issue number</label><input class="input" name="issue_number" value="<?=dw_h($issueControl)?>" required></div><div class="field wide"><label>Premium / result</label><input class="input" name="premium" placeholder="WinGo 5 · K3 1,2,3 · 5D 5,2,0,8,1" required></div><button class="btn primary" data-confirm="Save this result and settle eligible bets?">Save result</button></form><hr style="border:0;border-top:1px solid var(--line);margin:20px 0"><form method="post" class="toolbar"><?php dw_meta('wingo')?><input type="hidden" name="action" value="settle_pending_bets"><div class="field"><label>Game filter</label><input class="input" name="game_code" value="<?=dw_h($gameControl)?>"></div><div class="field"><label>Issue filter (optional)</label><input class="input" name="issue_number"></div><button class="btn warn" data-confirm="Run settlement for all eligible closed issues?">Settle pending</button></form></div></section></div>
   <section class="panel"><div class="panel-head"><h2>Saved engine rules</h2></div><div class="table-wrap"><table class="table"><thead><tr><th>Game</th><th>Mode / forced</th><th>Win rate</th><th>Fee</th><th>Payouts</th><th>Updated</th></tr></thead><tbody><?php foreach($settingsRows as $r):?><tr><td class="mono"><?=dw_h($r['game_code'])?></td><td><?=dw_badge($r['force_mode'])?> <?=dw_h($r['force_result'])?></td><td><?=dw_h($r['win_rate'])?>%</td><td><?=dw_h($r['fee_percent'])?>%</td><td class="small">No. <?=dw_h($r['payout_number'])?> · Color <?=dw_h($r['payout_color'])?> · Big <?=dw_h($r['payout_bigsmall'])?></td><td><?=dw_h($r['updated_at'])?></td></tr><?php endforeach;?></tbody></table></div></section>
   <div class="split"><section class="panel"><div class="panel-head"><h2>Recent results</h2></div><div class="table-wrap"><table class="table"><thead><tr><th>Game / issue</th><th>Result</th><th>Detail</th><th>Open time</th></tr></thead><tbody><?php foreach($results as $r):?><tr><td><?=dw_h($r['game_code'])?><div class="mono"><?=dw_h($r['issue_number'])?></div></td><td><strong><?=dw_h($r['premium'])?></strong></td><td><?=dw_h($r['color'])?> · <?=dw_h($r['big_small'])?></td><td><?=dw_h($r['open_time'])?></td></tr><?php endforeach;?></tbody></table></div></section><section class="panel"><div class="panel-head"><h2>Recent bets</h2></div><div class="table-wrap"><table class="table"><thead><tr><th>Order / user</th><th>Game</th><th>Stake</th><th>State</th></tr></thead><tbody><?php foreach($bets as $r):?><tr><td class="mono"><?=dw_h($r['order_no'])?><div><?=dw_h($r['username'])?></div></td><td><?=dw_h($r['game_code'])?><div class="small"><?=dw_h($r['issue_number'])?> · <?=dw_h($r['bet_content'])?></div></td><td>₹<?=dw_money((float)$r['real_amount']+(float)$r['fee'])?></td><td><?=dw_badge((int)$r['state']===2?'Pending':((int)$r['state']===1?'Win':'Loss'))?></td></tr><?php endforeach;?></tbody></table></div></section></div>

 <?php elseif($page==='gifts'):
   $gifts=dw_rows($conn,'SELECT * FROM gift_codes ORDER BY id DESC LIMIT 200');$claims=dw_rows($conn,'SELECT c.*,g.code,g.title,u.username FROM gift_code_claims c LEFT JOIN gift_codes g ON g.id=c.gift_code_id LEFT JOIN users u ON u.id=c.user_id ORDER BY c.id DESC LIMIT 100');?>
   <div class="split"><section class="panel"><div class="panel-head"><h2>Create gift code</h2></div><div class="panel-body"><form method="post" class="form-grid"><?php dw_meta('gifts')?><input type="hidden" name="action" value="gift_save"><div class="field"><label>Code</label><input class="input" name="code" required></div><div class="field"><label>Title</label><input class="input" name="title" value="Dhani Win Gift"></div><div class="field"><label>Amount</label><input class="input" type="number" step=".01" name="amount" required></div><div class="field"><label>Max claims</label><input class="input" type="number" name="max_claim" value="1"></div><div class="field"><label>Minimum approved deposit</label><input class="input" type="number" step=".01" name="min_recharge" value="0"></div><div class="field"><label>Expiry</label><input class="input" type="datetime-local" name="expires_at"></div><div class="field wide"><label>Admin note</label><input class="input" name="admin_note"></div><label class="check"><input type="checkbox" name="status" checked> Active</label><button class="btn primary">Create code</button></form></div></section>
   <section class="panel"><div class="panel-head"><h2>Claim summary</h2></div><div class="grid kpis" style="padding:18px;margin:0;grid-template-columns:1fr 1fr"><article class="kpi"><div class="label">Total claims</div><div class="value"><?=number_format(count($claims))?>+</div></article><article class="kpi"><div class="label">Recent value</div><div class="value">₹<?=dw_money(array_sum(array_column($claims,'amount')))?></div></article></div><div class="panel-body small">Every claim now stores claim number, claim time, balance before/after, IP and device. User Gift Record receives both <code>createTime</code> and <code>receiveTime</code>.</div></section></div>
   <section class="panel"><div class="panel-head"><h2>Gift codes</h2></div><div class="table-wrap"><table class="table"><thead><tr><th>Code</th><th>Amount</th><th>Claims</th><th>Rules</th><th>Status</th><th>Control</th></tr></thead><tbody><?php foreach($gifts as $r):?><tr><td><strong><?=dw_h($r['code'])?></strong><div class="small"><?=dw_h($r['title'])?></div></td><td>₹<?=dw_money($r['amount'])?></td><td><?=dw_h($r['claimed_count'])?> / <?=dw_h($r['max_claim'])?></td><td class="small">Min deposit ₹<?=dw_money($r['min_recharge'])?><div>Expiry <?=dw_h($r['expires_at']?:'Never')?></div></td><td><?=dw_badge($r['status']?'Active':'Disabled')?></td><td><form method="post"><?php dw_meta('gifts')?><input type="hidden" name="action" value="gift_toggle"><input type="hidden" name="id" value="<?=dw_h($r['id'])?>"><input type="hidden" name="status" value="<?=$r['status']?0:1?>"><button class="btn sm <?=$r['status']?'danger':'primary'?>"><?=$r['status']?'Disable':'Enable'?></button></form></td></tr><?php endforeach;?></tbody></table></div></section>
   <section class="panel"><div class="panel-head"><h2>Latest claims with timestamps</h2></div><div class="table-wrap"><table class="table"><thead><tr><th>Claim / code</th><th>User</th><th>Amount</th><th>Balance before → after</th><th>IP / device</th><th>Claim time</th></tr></thead><tbody><?php foreach($claims as $r):?><tr><td class="mono"><?=dw_h($r['claim_no'])?><div><?=dw_h($r['code'])?></div></td><td>#<?=dw_h($r['user_id'])?> <?=dw_h($r['username'])?></td><td class="amount plus">+₹<?=dw_money($r['amount'])?></td><td>₹<?=dw_money($r['balance_before'])?> → ₹<?=dw_money($r['balance_after'])?></td><td class="small"><?=dw_h($r['ip'])?><div class="mono"><?=dw_h($r['device_id'])?></div></td><td><?=dw_h($r['created_at'])?></td></tr><?php endforeach;?></tbody></table></div></section>

 <?php elseif($page==='payments'):
   $rows=dw_rows($conn,'SELECT * FROM payment_methods ORDER BY sort DESC,id DESC');?>
   <div class="split"><section class="panel"><div class="panel-head"><h2>Add UPI / Add USDT</h2><span class="badge">Live payment config</span></div><div class="panel-body"><form method="post" enctype="multipart/form-data" class="form-grid"><?php dw_meta('payments')?><input type="hidden" name="action" value="payment_save"><div class="field"><label>ID (0 = new)</label><input class="input" type="number" name="id" value="0"></div><div class="field"><label>Display name</label><input class="input" name="name" placeholder="UPI Primary / USDT TRC20" required></div><div class="field"><label>Payment type</label><select name="recharge_type"><option>UPI</option><option>BankCard</option><option>USDT</option><option>ARPay</option><option>Manual</option></select></div><div class="field"><label>Method kind</label><select name="method_kind"><option>UPI</option><option>USDT</option><option>BankCard</option><option>Manual</option></select></div><div class="field"><label>INR rate</label><input class="input" type="number" step=".0001" name="rate" value="1"></div><div class="field"><label>USDT Rate (₹ per USDT)</label><input class="input" type="number" step=".0001" name="usdt_rate" value="97"></div><div class="field"><label>Minimum</label><input class="input" type="number" step=".01" name="min_amount" value="100"></div><div class="field"><label>Maximum</label><input class="input" type="number" step=".01" name="max_amount" value="50000"></div><div class="field"><label>Gift ratio</label><input class="input" type="number" step=".01" name="gift_ratio" value="0"></div><div class="field"><label>Sort</label><input class="input" type="number" name="sort" value="100"></div><div class="field"><label>Add UPI</label><input class="input" name="upi_id" placeholder="merchant@upi"></div><div class="field"><label>UPI account name</label><input class="input" name="upi_name"></div><div class="field wide"><label>Add USDT address</label><input class="input" name="usdt_address" placeholder="TRC20 wallet address"></div><div class="field"><label>USDT network</label><select name="network"><option>TRC20</option><option>ERC20</option><option>BEP20</option></select></div><div class="field"><label>Add UPI / USDT Image</label><input class="input" type="file" name="payment_image" accept="image/png,image/jpeg,image/webp,image/gif"></div><div class="field wide"><label>Existing image URL (optional)</label><input class="input" name="qr_image"></div><div class="field wide"><label>User instructions</label><textarea name="note"></textarea></div><label class="check"><input type="checkbox" name="state" checked> Enabled</label><label class="check"><input type="checkbox" name="deposit_enabled" checked> Deposit enabled</label><label class="check"><input type="checkbox" name="withdraw_enabled" checked> Withdraw enabled</label><button class="btn primary">Save UPI / USDT</button></form></div></section>
   <section class="panel"><div class="panel-head"><h2>Payment Workflow</h2></div><div class="panel-body"><div class="workflow-list"><a href="?page=recharges&status=PendingReview">Deposit Update <strong>→</strong></a><a href="?page=withdrawals&status=pending">Withdraw Apply <strong>→</strong></a><a href="?page=withdrawals&method=UPI">UPI Withdraw <strong>→</strong></a><a href="?page=withdrawals&status=approved">Withdraw Sent <strong>→</strong></a><a href="?page=withdrawals&status=rejected">Withdraw Reject <strong>→</strong></a></div><p class="small muted">Approved deposits create the configured turnover requirement. Rejected reserved withdrawals are refunded through the detailed wallet ledger.</p></div></section></div>
   <section class="panel"><div class="panel-head"><h2>Configured UPI / USDT Methods</h2></div><div class="table-wrap"><table class="table"><thead><tr><th>ID / name</th><th>Type</th><th>Rates</th><th>Limits</th><th>Account / network</th><th>Image</th><th>Use</th><th>Control</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td>#<?=dw_h($r['id'])?> <strong><?=dw_h($r['name'])?></strong><div class="small">Sort <?=dw_h($r['sort'])?></div></td><td><?=dw_badge($r['recharge_type'])?></td><td>INR <?=dw_h($r['rate'])?><div>USDT ₹<?=dw_h($r['usdt_rate'])?></div></td><td>₹<?=dw_money($r['min_amount'])?> – ₹<?=dw_money($r['max_amount'])?></td><td><?=dw_h($r['upi_id']?:$r['usdt_address'])?><div class="small"><?=dw_h($r['network'])?></div></td><td><?php if($r['qr_image']):?><img class="payment-thumb" src="<?=dw_h($r['qr_image'])?>" alt="Payment QR"><?php else:?><span class="muted">No image</span><?php endif;?></td><td><?=dw_badge($r['deposit_enabled']?'Deposit':'No deposit')?> <?=dw_badge($r['withdraw_enabled']?'Withdraw':'No withdraw')?></td><td><form method="post"><?php dw_meta('payments')?><input type="hidden" name="action" value="payment_toggle"><input type="hidden" name="id" value="<?=dw_h($r['id'])?>"><input type="hidden" name="state" value="<?=$r['state']?0:1?>"><button class="btn sm"><?=$r['state']?'Disable':'Enable'?></button></form></td></tr><?php endforeach;?></tbody></table></div></section>

 <?php elseif($page==='content'):
   $banners=dw_rows($conn,'SELECT * FROM banners ORDER BY sort DESC,id DESC');$notices=dw_rows($conn,'SELECT * FROM notifications ORDER BY id DESC LIMIT 200');?>
   <div class="split"><section class="panel"><div class="panel-head"><h2>New banner</h2></div><div class="panel-body"><form method="post" class="form-grid"><?php dw_meta('content')?><input type="hidden" name="action" value="content_save"><input type="hidden" name="kind" value="banner"><div class="field"><label>Name</label><input class="input" name="name" required></div><div class="field"><label>Sort</label><input class="input" type="number" name="sort" value="100"></div><div class="field wide"><label>Image URL</label><input class="input" name="icon_url" required></div><div class="field wide"><label>Jump URL/detail</label><input class="input" name="jump_detail"></div><label class="check"><input type="checkbox" name="status" checked> Active</label><button class="btn primary">Add banner</button></form></div></section>
   <section class="panel"><div class="panel-head"><h2>New notification</h2></div><div class="panel-body"><form method="post" class="form-grid"><?php dw_meta('content')?><input type="hidden" name="action" value="content_save"><input type="hidden" name="kind" value="notification"><div class="field"><label>Title</label><input class="input" name="title" required></div><div class="field"><label>Type</label><select name="type"><option>notice</option><option>promotion</option><option>maintenance</option></select></div><div class="field wide"><label>Content</label><textarea name="content"></textarea></div><div class="field wide"><label>Jump URL</label><input class="input" name="jump_url"></div><label class="check"><input type="checkbox" name="status" checked> Active</label><button class="btn primary">Publish</button></form></div></section></div>
   <section class="panel"><div class="panel-head"><h2>Banners</h2></div><div class="table-wrap"><table class="table"><thead><tr><th>Preview</th><th>Name</th><th>Jump</th><th>Sort</th><th>Status</th><th>Control</th></tr></thead><tbody><?php foreach($banners as $r):?><tr><td><img src="<?=dw_h($r['icon_url'])?>" alt="" width="90" height="44" loading="lazy" style="object-fit:cover;border-radius:6px"></td><td><?=dw_h($r['name'])?></td><td class="small mono"><?=dw_h($r['jump_detail'])?></td><td><?=dw_h($r['sort'])?></td><td><?=dw_badge($r['status']?'Active':'Disabled')?></td><td><form method="post"><?php dw_meta('content')?><input type="hidden" name="action" value="content_toggle"><input type="hidden" name="kind" value="banner"><input type="hidden" name="id" value="<?=dw_h($r['id'])?>"><input type="hidden" name="status" value="<?=$r['status']?0:1?>"><button class="btn sm"><?=$r['status']?'Disable':'Enable'?></button></form></td></tr><?php endforeach;?></tbody></table></div></section>
   <section class="panel"><div class="panel-head"><h2>Notifications</h2></div><div class="table-wrap"><table class="table"><thead><tr><th>Title</th><th>Content</th><th>Type</th><th>Created</th><th>Status</th><th>Control</th></tr></thead><tbody><?php foreach($notices as $r):?><tr><td><strong><?=dw_h($r['title'])?></strong></td><td><?=dw_h(strlen((string)$r['content'])>100?substr((string)$r['content'],0,100).'…':(string)$r['content'])?></td><td><?=dw_h($r['type'])?></td><td><?=dw_h($r['created_at'])?></td><td><?=dw_badge($r['status']?'Active':'Disabled')?></td><td><form method="post"><?php dw_meta('content')?><input type="hidden" name="action" value="content_toggle"><input type="hidden" name="kind" value="notification"><input type="hidden" name="id" value="<?=dw_h($r['id'])?>"><input type="hidden" name="status" value="<?=$r['status']?0:1?>"><button class="btn sm"><?=$r['status']?'Disable':'Enable'?></button></form></td></tr><?php endforeach;?></tbody></table></div></section>

 <?php elseif($page==='vip'):
   $rows=dw_rows($conn,'SELECT * FROM vip_levels ORDER BY level');?>
   <section class="panel"><div class="panel-head"><h2>Add or update VIP level</h2></div><div class="panel-body"><form method="post" class="toolbar"><?php dw_meta('vip')?><input type="hidden" name="action" value="vip_save"><?php foreach([['level','Level','number','1'],['name','Name','text','VIP 1'],['deposit_required','Deposit required','number','0'],['bet_required','Bet required','number','0'],['level_reward','Level reward','number','0'],['weekly_reward','Weekly reward','number','0'],['monthly_reward','Monthly reward','number','0']] as $f):?><div class="field"><label><?=$f[1]?></label><input class="input" type="<?=$f[2]?>" step="<?=$f[2]==='number'?'.01':'1'?>" name="<?=$f[0]?>" value="<?=$f[3]?>" required></div><?php endforeach;?><label class="check"><input type="checkbox" name="status" checked> Enabled</label><button class="btn primary">Save level</button></form></div><div class="table-wrap"><table class="table"><thead><tr><th>Level</th><th>Requirements</th><th>Rewards</th><th>Status</th><th>Control</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><strong><?=dw_h($r['name'])?></strong><div>Level <?=dw_h($r['level'])?></div></td><td>Deposit ₹<?=dw_money($r['deposit_required'])?><div>Bet ₹<?=dw_money($r['bet_required'])?></div></td><td>Level ₹<?=dw_money($r['level_reward'])?> · Weekly ₹<?=dw_money($r['weekly_reward'])?> · Monthly ₹<?=dw_money($r['monthly_reward'])?></td><td><?=dw_badge($r['status']?'Active':'Disabled')?></td><td><form method="post"><?php dw_meta('vip')?><input type="hidden" name="action" value="vip_toggle"><input type="hidden" name="id" value="<?=dw_h($r['id'])?>"><input type="hidden" name="status" value="<?=$r['status']?0:1?>"><button class="btn sm"><?=$r['status']?'Disable':'Enable'?></button></form></td></tr><?php endforeach;?></tbody></table></div></section>

 <?php elseif($page==='tasks'):
   $rows=dw_rows($conn,'SELECT * FROM activity_tasks ORDER BY sort DESC,id');?>
   <section class="panel"><div class="panel-head"><h2>Activity tasks and claim rules</h2></div><div class="panel-body"><form method="post" class="toolbar"><?php dw_meta('tasks')?><input type="hidden" name="action" value="task_save"><div class="field"><label>Code</label><input class="input" name="code" required></div><div class="field"><label>Title</label><input class="input" name="title" required></div><div class="field"><label>Type</label><select name="task_type"><option>manual</option><option>deposit</option><option>deposit_count</option><option>withdraw</option><option>telegram</option></select></div><div class="field"><label>Target</label><input class="input" type="number" step=".01" name="target_value" value="1"></div><div class="field"><label>Reward</label><input class="input" type="number" step=".01" name="reward" value="1"></div><div class="field"><label>Sort</label><input class="input" type="number" name="sort" value="100"></div><label class="check"><input type="checkbox" name="status" checked> Active</label><button class="btn primary">Add task</button></form></div><div class="table-wrap"><table class="table"><thead><tr><th>Code</th><th>Task</th><th>Target</th><th>Reward</th><th>Sort</th><th>Status</th><th>Control</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td class="mono"><?=dw_h($r['code'])?></td><td><?=dw_h($r['title'])?><div class="small"><?=dw_h($r['task_type'])?></div></td><td><?=dw_h($r['target_value'])?></td><td>₹<?=dw_money($r['reward'])?></td><td><?=dw_h($r['sort'])?></td><td><?=dw_badge($r['status']?'Active':'Disabled')?></td><td><form method="post"><?php dw_meta('tasks')?><input type="hidden" name="action" value="task_toggle"><input type="hidden" name="id" value="<?=dw_h($r['id'])?>"><input type="hidden" name="status" value="<?=$r['status']?0:1?>"><button class="btn sm"><?=$r['status']?'Disable':'Enable'?></button></form></td></tr><?php endforeach;?></tbody></table></div></section>

 <?php elseif($page==='wheels'):
   $iw=dw_setting($conn,'invited_wheel_settings',[]);$rw=dw_setting($conn,'recharge_wheel_config',[]);$records=dw_rows($conn,'SELECT r.*,u.username FROM recharge_wheel_records r LEFT JOIN users u ON u.id=r.user_id ORDER BY r.id DESC LIMIT 50');?>
   <div class="split"><section class="panel"><div class="panel-head"><h2>Invite wheel</h2></div><div class="panel-body"><form method="post" class="form-grid"><?php dw_meta('wheels')?><input type="hidden" name="action" value="wheel_settings_save"><input type="hidden" name="kind" value="invited"><div class="field"><label>Cashout minimum</label><input class="input" type="number" step=".01" name="min_withdraw_amount" value="<?=dw_h($iw['min_withdraw_amount']??500)?>"></div><div class="field"><label>Turnover multiplier</label><input class="input" type="number" step=".1" name="turnover_multiplier" value="<?=dw_h($iw['turnover_multiplier']??0)?>"></div><div class="field"><label>Free reward min</label><input class="input" type="number" step=".01" name="free_spin_min" value="<?=dw_h($iw['free_spin_min']??.1)?>"></div><div class="field"><label>Free reward max</label><input class="input" type="number" step=".01" name="free_spin_max" value="<?=dw_h($iw['free_spin_max']??3)?>"></div><div class="field"><label>Maximum spin reward</label><input class="input" type="number" step=".01" name="max_spin_reward" value="<?=dw_h($iw['max_spin_reward']??3)?>"></div><label class="check"><input type="checkbox" name="enabled" <?=!empty($iw['enabled'])?'checked':''?>> Enabled</label><button class="btn primary">Save invite wheel</button></form></div></section>
   <section class="panel"><div class="panel-head"><h2>Recharge wheel</h2></div><div class="panel-body"><form method="post" class="form-grid"><?php dw_meta('wheels')?><input type="hidden" name="action" value="wheel_settings_save"><input type="hidden" name="kind" value="recharge"><div class="field"><label>Approved deposit required</label><input class="input" type="number" step=".01" name="need_recharge_amount" value="<?=dw_h($rw['needRechargeAmount']??100)?>"></div><div class="field"><label>Reward-up threshold</label><input class="input" type="number" step=".01" name="reward_up_amount" value="<?=dw_h($rw['rewardUpAmount']??20000)?>"></div><div class="field"><label>Special wheel unlock</label><input class="input" type="number" step=".01" name="special_unlock_amount" value="<?=dw_h($rw['specialWheelUnlockAmount']??50000)?>"></div><label class="check"><input type="checkbox" name="enabled" <?=!empty($rw['enabled'])?'checked':''?>> Enabled</label><label class="check"><input type="checkbox" name="require_approved" <?=!empty($rw['requireApprovedRecharge'])?'checked':''?>> Require approved deposit</label><button class="btn primary">Save recharge wheel</button></form></div></section></div>
   <section class="panel"><div class="panel-head"><h2>Recent recharge wheel rewards</h2></div><div class="table-wrap"><table class="table"><thead><tr><th>Order</th><th>User</th><th>Wheel</th><th>Reward</th><th>Time</th></tr></thead><tbody><?php foreach($records as $r):?><tr><td class="mono"><?=dw_h($r['order_no'])?></td><td><?=dw_h($r['username'])?></td><td><?=dw_h($r['recharge_wheel_type'])?></td><td class="amount plus">+₹<?=dw_money($r['reward_amount'])?></td><td><?=dw_h($r['created_at'])?></td></tr><?php endforeach;?></tbody></table></div></section>

 <?php elseif($page==='support'):
   $status=(string)($_GET['status']??'all');$where=in_array($status,['Pending','Processing','Answered','Closed','Rejected'],true)?"WHERE w.status='".$conn->real_escape_string($status)."'":'';$rows=dw_rows($conn,"SELECT w.*,u.username FROM work_orders w LEFT JOIN users u ON u.id=w.user_id $where ORDER BY w.id DESC LIMIT 200");?>
   <section class="panel"><div class="panel-head"><h2>Support tickets</h2><form><input type="hidden" name="page" value="support"><select name="status" onchange="this.form.submit()"><option value="all">All statuses</option><?php foreach(['Pending','Processing','Answered','Closed','Rejected'] as $s):?><option <?=$status===$s?'selected':''?>><?=$s?></option><?php endforeach;?></select></form></div><div class="table-wrap"><table class="table"><thead><tr><th>Ticket / user</th><th>Subject</th><th>Message</th><th>Status</th><th>Reply</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td class="mono"><?=dw_h($r['ticket_no'])?><div><?=dw_h($r['username'])?></div></td><td><?=dw_h($r['title'])?><div class="small"><?=dw_h($r['type_name'])?> · <?=dw_h($r['contact'])?></div></td><td><?=nl2br(dw_h($r['content']))?><?php if($r['admin_reply']):?><div class="notice small"><strong>Reply:</strong> <?=dw_h($r['admin_reply'])?></div><?php endif;?></td><td><?=dw_badge($r['status'])?><div class="small"><?=dw_h($r['created_at'])?></div></td><td><details class="action-box"><summary class="btn sm primary">Respond</summary><form method="post" class="popover"><?php dw_meta('support')?><input type="hidden" name="action" value="support_update"><input type="hidden" name="id" value="<?=dw_h($r['id'])?>"><div class="field"><label>Status</label><select name="status"><?php foreach(['Processing','Answered','Closed','Rejected'] as $s):?><option <?=$r['status']===$s?'selected':''?>><?=$s?></option><?php endforeach;?></select></div><div class="field"><label>Reply</label><textarea name="admin_reply"><?=dw_h($r['admin_reply'])?></textarea></div><button class="btn primary">Save reply</button></form></details></td></tr><?php endforeach;?></tbody></table></div></section>

 <?php elseif($page==='agents'):
   $rows=dw_rows($conn,"SELECT u.*,p.username parent_username,(SELECT COALESCE(SUM(commission_amount),0) FROM agent_commissions c WHERE c.user_id=u.id) commission FROM users u LEFT JOIN users p ON p.id=u.agent_parent_id WHERE u.role='user' AND (u.is_agent=1 OR u.agent_parent_id IS NOT NULL) ORDER BY u.id DESC LIMIT 300");$salaryRows=dw_rows($conn,"SELECT s.*,u.username FROM agent_salary_records s LEFT JOIN users u ON u.id=s.agent_user_id ORDER BY s.id DESC LIMIT 100");?>
   <div class="split"><section class="panel"><div class="panel-head"><h2>Daily Salary</h2><span class="badge">Idempotent payment</span></div><div class="panel-body"><form method="post" class="form-grid"><?php dw_meta('agents')?><input type="hidden" name="action" value="agent_salary_run"><div class="field"><label>Salary date</label><input class="input" type="date" name="period_date" value="<?=dw_h(date('Y-m-d'))?>" required></div><div class="field"><label>&nbsp;</label><button class="btn primary" data-confirm="Pay configured daily salary to every active agent for this date?">Run Daily Salary</button></div></form><p class="small muted">Each agent can be paid only once per date. Re-running safely skips already-paid records and every credit appears in Balance Record.</p></div></section><section class="panel"><div class="panel-head"><h2>Agent User Summary</h2></div><div class="panel-body grid mini-kpis"><article class="mini-kpi"><span>Agents</span><strong><?=number_format((int)dw_scalar($conn,"SELECT COUNT(*) FROM users WHERE role='user' AND is_agent=1"))?></strong></article><article class="mini-kpi"><span>Salary / day</span><strong>₹<?=dw_money(dw_scalar($conn,"SELECT COALESCE(SUM(agent_salary),0) FROM users WHERE role='user' AND is_agent=1 AND status=1"))?></strong></article><article class="mini-kpi"><span>Paid today</span><strong>₹<?=dw_money(dw_scalar($conn,"SELECT COALESCE(SUM(salary_amount),0) FROM agent_salary_records WHERE period_date=CURDATE() AND status='paid'"))?></strong></article></div></section></div>
   <section class="panel"><div class="panel-head"><h2>Agent hierarchy and commission overview</h2></div><div class="table-wrap"><table class="table"><thead><tr><th>Agent / user</th><th>Parent</th><th>Salary</th><th>Commission</th><th>Team count</th><th>Control</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td>#<?=dw_h($r['id'])?> <?=dw_h($r['username'])?><div><?=dw_badge($r['is_agent']?'Agent':'Member')?></div></td><td><?=dw_h($r['parent_username']?:'—')?></td><td>₹<?=dw_money($r['agent_salary'])?></td><td>₹<?=dw_money($r['commission'])?></td><td><?=number_format((int)dw_scalar($conn,'SELECT COUNT(*) FROM users WHERE agent_parent_id='.(int)$r['id']))?></td><td><details class="action-box"><summary class="btn sm">Edit</summary><form method="post" class="popover"><?php dw_meta('agents')?><input type="hidden" name="action" value="agent_update"><input type="hidden" name="id" value="<?=dw_h($r['id'])?>"><label class="check"><input type="checkbox" name="is_agent" <?=$r['is_agent']?'checked':''?>> Agent account</label><div class="field"><label>Parent user ID</label><input class="input" type="number" name="agent_parent_id" value="<?=dw_h($r['agent_parent_id'])?>"></div><div class="field"><label>Salary amount</label><input class="input" type="number" step=".01" name="agent_salary" value="<?=dw_h($r['agent_salary'])?>"></div><button class="btn primary">Save hierarchy</button></form></details></td></tr><?php endforeach;?></tbody></table></div></section>
   <section class="panel"><div class="panel-head"><h2>Salary Payment History</h2></div><div class="table-wrap"><table class="table"><thead><tr><th>Date</th><th>Agent</th><th>Team deposit</th><th>Team bet</th><th>Salary</th><th>Status</th><th>Paid at</th></tr></thead><tbody><?php foreach($salaryRows as $r):?><tr><td><?=dw_h($r['period_date'])?></td><td>#<?=dw_h($r['agent_user_id'])?> <?=dw_h($r['username'])?></td><td>₹<?=dw_money($r['team_deposit'])?></td><td>₹<?=dw_money($r['team_bet'])?></td><td class="amount plus">+₹<?=dw_money($r['salary_amount'])?></td><td><?=dw_badge($r['status'])?></td><td><?=dw_h($r['created_at'])?></td></tr><?php endforeach;?></tbody></table></div></section>

 <?php elseif($page==='risk'):
   $rows=dw_rows($conn,"SELECT r.*,u.username FROM risk_flags r LEFT JOIN users u ON u.id=r.user_id ORDER BY FIELD(r.status,'open','reviewing','resolved','dismissed'),FIELD(r.severity,'critical','high','medium','low'),r.id DESC LIMIT 300");$duplicates=dw_rows($conn,"SELECT ip_last,COUNT(*) account_count,GROUP_CONCAT(CONCAT('#',id,' ',username) ORDER BY id SEPARATOR ', ') accounts,MAX(last_login_at) last_seen FROM users WHERE role='user' AND ip_last<>'' GROUP BY ip_last HAVING COUNT(*)>1 ORDER BY account_count DESC,last_seen DESC LIMIT 200");?>
   <section class="panel"><div class="panel-head"><div><h2>Check Same IP</h2><span class="small muted">Duplicate-account and shared-network review</span></div><form method="post"><?php dw_meta('risk')?><input type="hidden" name="action" value="same_ip_scan"><button class="btn primary" data-confirm="Scan all user IPs and refresh duplicate flags?">Run Same-IP Scan</button></form></div><div class="table-wrap"><table class="table"><thead><tr><th>IP address</th><th>Accounts</th><th>Users</th><th>Last login</th></tr></thead><tbody><?php if(!$duplicates):?><tr><td colspan="4" class="empty">No duplicate IP groups found.</td></tr><?php else:foreach($duplicates as $r):?><tr><td class="mono"><?=dw_h($r['ip_last'])?></td><td><?=dw_badge($r['account_count'].' accounts')?></td><td><?=dw_h($r['accounts'])?></td><td><?=dw_h($r['last_seen']?:'Never')?></td></tr><?php endforeach;endif;?></tbody></table></div></section>
   <div class="split"><section class="panel"><div class="panel-head"><h2>Create risk flag</h2></div><div class="panel-body"><form method="post" class="form-grid"><?php dw_meta('risk')?><input type="hidden" name="action" value="risk_save"><div class="field"><label>User ID</label><input class="input" type="number" name="user_id" required></div><div class="field"><label>Flag type</label><select name="flag_type"><option>duplicate_account</option><option>suspicious_payment</option><option>withdrawal_review</option><option>bonus_abuse</option><option>manual_review</option></select></div><div class="field"><label>Severity</label><select name="severity"><option>medium</option><option>low</option><option>high</option><option>critical</option></select></div><div class="field wide"><label>Reason</label><textarea name="reason" required></textarea></div><button class="btn primary">Open flag</button></form></div></section><section class="panel"><div class="panel-head"><h2>Risk queue</h2></div><div class="grid kpis" style="padding:18px;margin:0;grid-template-columns:1fr 1fr"><?php foreach(['open','reviewing','critical','resolved'] as $s):?><article class="kpi"><div class="label"><?=ucfirst($s)?></div><div class="value"><?=number_format((int)dw_scalar($conn,$s==='critical'?"SELECT COUNT(*) FROM risk_flags WHERE severity='critical' AND status IN ('open','reviewing')":"SELECT COUNT(*) FROM risk_flags WHERE status='".$s."'"))?></div></article><?php endforeach;?></div></section></div>
   <section class="panel"><div class="table-wrap"><table class="table"><thead><tr><th>User</th><th>Flag</th><th>Severity</th><th>Reason</th><th>Status</th><th>Update</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td>#<?=dw_h($r['user_id'])?> <?=dw_h($r['username'])?></td><td class="mono"><?=dw_h($r['flag_type'])?><div class="small"><?=dw_h($r['created_at'])?></div></td><td><?=dw_badge($r['severity'])?></td><td><?=dw_h($r['reason'])?></td><td><?=dw_badge($r['status'])?></td><td><form method="post" class="toolbar"><?php dw_meta('risk')?><input type="hidden" name="action" value="risk_save"><input type="hidden" name="id" value="<?=dw_h($r['id'])?>"><select name="status"><option>open</option><option <?=$r['status']==='reviewing'?'selected':''?>>reviewing</option><option <?=$r['status']==='resolved'?'selected':''?>>resolved</option><option <?=$r['status']==='dismissed'?'selected':''?>>dismissed</option></select><button class="btn sm">Save</button></form></td></tr><?php endforeach;?></tbody></table></div></section>

 <?php elseif($page==='settings'):
   $s=site_settings();$bools=['home_enabled'=>'Home page','popup_enabled'=>'Popups','maintenance_enabled'=>'Maintenance mode','gift_enabled'=>'Gift codes','recharge_enabled'=>'Deposits','withdraw_enabled'=>'Withdrawals','vip_enabled'=>'VIP','agent_enabled'=>'Agents','invite_enabled'=>'Invites','lottery_enabled'=>'Lottery','wingo_enabled'=>'WinGo','k3_enabled'=>'K3','d5_enabled'=>'5D','moto_enabled'=>'Moto','trx_enabled'=>'TRX WinGo','support_chat_enabled'=>'Support','wager_lock_enabled'=>'Turnover lock'];?>
   <section class="panel"><div class="panel-head"><h2>Site, finance and feature controls</h2></div><div class="panel-body"><form method="post"><?php dw_meta('settings')?><input type="hidden" name="action" value="site_settings_save"><div class="three"><?php foreach($bools as $key=>$label):?><label class="check"><input type="checkbox" name="<?=dw_h($key)?>" <?=!empty($s[$key])?'checked':''?>> <?=dw_h($label)?></label><?php endforeach;?></div><hr style="border:0;border-top:1px solid var(--line);margin:22px 0"><div class="form-grid"><div class="field wide"><label>Maintenance message</label><textarea name="maintenance_text"><?=dw_h($s['maintenance_text']??'')?></textarea></div><div class="field"><label>Minimum withdrawal</label><input class="input" type="number" step=".01" name="min_withdraw_amount" value="<?=dw_h($s['min_withdraw_amount']??110)?>"></div><div class="field"><label>Daily withdrawal count</label><input class="input" type="number" name="withdraw_daily_limit" value="<?=dw_h($s['withdraw_daily_limit']??3)?>"></div><div class="field"><label>Daily withdrawal amount</label><input class="input" type="number" step=".01" name="withdraw_daily_amount_limit" value="<?=dw_h($s['withdraw_daily_amount_limit']??50000)?>"></div><div class="field"><label>Deposit turnover multiplier</label><input class="input" type="number" step=".1" name="deposit_turnover_multiplier" value="<?=dw_h($s['deposit_turnover_multiplier']??1)?>"></div><div class="field"><label>Deposit-gift turnover multiplier</label><input class="input" type="number" step=".1" name="recharge_gift_turnover_multiplier" value="<?=dw_h($s['recharge_gift_turnover_multiplier']??0)?>"></div><div class="field"><label>Gift-code turnover multiplier</label><input class="input" type="number" step=".1" name="gift_code_turnover_multiplier" value="<?=dw_h($s['gift_code_turnover_multiplier']??1)?>"></div><div class="field"><label>Telegram URL</label><input class="input" name="telegram_url" value="<?=dw_h($s['telegram_url']??'')?>"></div><div class="field"><label>Service URL</label><input class="input" name="service_url" value="<?=dw_h($s['service_url']??'')?>"></div></div><div style="margin-top:18px"><button class="btn primary" data-confirm="Apply these live site settings?">Save settings</button></div></form></div></section>

 <?php elseif($page==='admins'):
   $admins=dw_rows($conn,"SELECT u.id,u.username,u.nickname,u.status,u.must_change_password,u.last_login_at,p.permissions,p.status permission_status FROM users u LEFT JOIN admin_permissions p ON p.admin_user=u.username WHERE u.role='admin' ORDER BY u.id");$allPerms=['dashboard','users','finance','recharges','withdrawals','wagers','games','wingo','gifts','payments','content','vip','tasks','wheels','support','agents','risk','settings','admins','audit','system'];?>
   <div class="split"><section class="panel"><div class="panel-head"><h2>Add Admin</h2><span class="badge">Role based</span></div><div class="panel-body"><form method="post" class="form-grid"><?php dw_meta('admins')?><input type="hidden" name="action" value="admin_create"><div class="field"><label>Username</label><input class="input" name="username" required></div><div class="field"><label>Display name</label><input class="input" name="nickname"></div><div class="field wide"><label>Temporary password (10+ chars)</label><input class="input" type="password" minlength="10" name="password" required></div><button class="btn primary">Create Admin</button></form></div></section><section class="panel"><div class="panel-head"><h2>Admin Password</h2></div><div class="panel-body"><form method="post" class="form-grid"><?php dw_meta('admins')?><input type="hidden" name="action" value="change_own_password"><div class="field wide"><label>Current password</label><input class="input" type="password" name="current_password" required></div><div class="field"><label>New password (10+)</label><input class="input" type="password" minlength="10" name="new_password" required></div><div class="field"><label>Confirm password</label><input class="input" type="password" minlength="10" name="confirm_password" required></div><button class="btn primary" data-confirm="Change your admin password?">Update Password</button></form><p class="small muted">Super Admin has full access. Other admins receive only selected module permissions and every change is audited.</p></div></section></div>
   <section class="panel"><div class="panel-head"><h2>Admin accounts and roles</h2></div><div class="table-wrap"><table class="table"><thead><tr><th>Admin</th><th>Last login</th><th>Permissions</th><th>Password</th></tr></thead><tbody><?php foreach($admins as $r):$selected=json_decode((string)$r['permissions'],true);if(!is_array($selected))$selected=[];$isRootAdmin=(int)$r['id']===1||strtolower((string)$r['username'])==='admin';?><tr><td>#<?=dw_h($r['id'])?> <strong><?=dw_h($r['nickname'])?></strong><div class="mono"><?=dw_h($r['username'])?></div><?=dw_badge($r['must_change_password']?'Password change due':'Active')?></td><td><?=dw_h($r['last_login_at']?:'Never')?></td><td><?php if($isRootAdmin):?><span class="badge">Super admin</span><?php else:?><details class="action-box"><summary class="btn sm">Edit role</summary><form method="post" class="popover left" style="width:420px"><?php dw_meta('admins')?><input type="hidden" name="action" value="admin_permissions_save"><input type="hidden" name="id" value="<?=dw_h($r['id'])?>"><div class="form-grid"><?php foreach($allPerms as $perm):?><label class="check"><input type="checkbox" name="permissions[]" value="<?=dw_h($perm)?>" <?=in_array($perm,$selected,true)?'checked':''?>> <?=dw_h($perm)?></label><?php endforeach;?></div><label class="check"><input type="checkbox" name="permission_status" <?=(int)$r['permission_status']===1?'checked':''?>> Permission set active</label><button class="btn primary">Save permissions</button></form></details><?php endif;?></td><td><?php if((int)$r['id']!==(int)$admin['id']&&!$isRootAdmin):?><details class="action-box"><summary class="btn sm warn">Reset</summary><form method="post" class="popover"><?php dw_meta('admins')?><input type="hidden" name="action" value="admin_reset_password"><input type="hidden" name="id" value="<?=dw_h($r['id'])?>"><div class="field"><label>Temporary password</label><input class="input" type="password" minlength="10" name="password" required></div><button class="btn danger" data-confirm="Reset this admin password?">Reset password</button></form></details><?php else:?><span class="small muted">Protected super admin</span><?php endif;?></td></tr><?php endforeach;?></tbody></table></div></section>

 <?php elseif($page==='audit'):
   $action=trim((string)($_GET['action_filter']??''));$where=$action!==''?"WHERE a.action='".$conn->real_escape_string($action)."'":'';$rows=dw_rows($conn,"SELECT a.*,u.username FROM admin_audit_logs a LEFT JOIN users u ON u.id=a.admin_user_id $where ORDER BY a.id DESC LIMIT 500");?>
   <section class="panel"><div class="panel-head"><h2>Immutable admin action trail</h2><a class="btn sm" href="?page=audit&export=audit">Export CSV</a></div><div class="panel-body"><form class="toolbar"><input type="hidden" name="page" value="audit"><div class="field"><label>Exact action</label><input class="input" name="action_filter" value="<?=dw_h($action)?>"></div><button class="btn primary">Filter</button></form></div><div class="table-wrap"><table class="table"><thead><tr><th>Time / actor</th><th>Action</th><th>Target</th><th>IP</th><th>Structured detail</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><?=dw_h($r['created_at'])?><div><?=dw_h($r['username']?:'System')?> #<?=dw_h($r['admin_user_id'])?></div></td><td class="mono"><?=dw_h($r['action'])?></td><td><?=dw_h($r['target_type'])?> #<?=dw_h($r['target_id'])?></td><td class="mono"><?=dw_h($r['ip'])?></td><td><details><summary>View JSON</summary><pre class="code"><?=dw_h(json_encode(json_decode((string)$r['data_json'],true),JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES))?></pre></details></td></tr><?php endforeach;?></tbody></table></div></section>

 <?php elseif($page==='system'):
   $tables=['users','recharge_orders','withdraw_requests','financial_records','wager_requirements','lottery_bets','lottery_results','gift_codes','admin_audit_logs','risk_flags','agent_commissions','work_orders','third_party_providers','third_party_launch_sessions','third_party_wallet_transactions'];$checks=[];foreach($tables as $t){$safe=$conn->real_escape_string($t);$checks[$t]=(int)dw_scalar($conn,"SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='$safe'")===1;}$disk=@disk_free_space(dirname(__DIR__));$debugFiles=['turntable_doctor.php','download_missing_assets.php','scratch_safe.php','scratch_check.php'];?>
   <div class="grid kpis"><article class="kpi"><div class="label">Database</div><div class="value"><?=dw_badge(count(array_filter($checks))===count($checks)?'Healthy':'Check')?></div><div class="sub"><?=count(array_filter($checks))?> / <?=count($checks)?> critical tables</div></article><article class="kpi"><div class="label">PHP version</div><div class="value"><?=dw_h(PHP_VERSION)?></div></article><article class="kpi"><div class="label">Free disk</div><div class="value"><?=dw_h($disk!==false?round($disk/1073741824,1).' GB':'Unknown')?></div></article><article class="kpi"><div class="label">Application mode</div><div class="value"><?=defined('DEMO_MODE')&&DEMO_MODE?'Demo wallet':'Configured'?></div></article></div>
   <div class="split"><section class="panel"><div class="panel-head"><h2>Critical tables</h2></div><div class="table-wrap"><table class="table"><thead><tr><th>Table</th><th>Status</th><th>Rows</th></tr></thead><tbody><?php foreach($checks as $table=>$ok):?><tr><td class="mono"><?=dw_h($table)?></td><td><?=dw_badge($ok?'Available':'Missing')?></td><td><?=$ok?number_format((int)dw_scalar($conn,'SELECT COUNT(*) FROM '.$table)):'—'?></td></tr><?php endforeach;?></tbody></table></div></section><section class="panel"><div class="panel-head"><h2>Runtime configuration</h2></div><div class="panel-body metric-list"><div class="metric-row"><span>Auto installer</span><div></div><strong><?=defined('AUTO_INSTALL_TABLES')&&AUTO_INSTALL_TABLES?'On':'Off'?></strong></div><div class="metric-row"><span>MySQL charset</span><div></div><strong>utf8mb4</strong></div><div class="metric-row"><span>HTTPS detected</span><div></div><strong><?=(!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off')?'Yes':'No'?></strong></div><div class="metric-row"><span>Open withdrawals</span><div></div><strong><?=dw_scalar($conn,"SELECT COUNT(*) FROM withdraw_requests WHERE status='pending'")?></strong></div><div class="metric-row"><span>Pending deposits</span><div></div><strong><?=dw_scalar($conn,"SELECT COUNT(*) FROM recharge_orders WHERE status IN ('Wait','PendingReview')")?></strong></div></div></section></div>
   <section class="panel"><div class="panel-head"><h2>Deployment checklist</h2></div><div class="panel-body"><ol><li>Fresh install: import <code>DhaniWin-V34-Database.sql</code>. Existing V33: run <code>database_v34_migration.sql</code> after taking a full backup.</li><li>Update database credentials and a long random <code>APP_SECRET</code> in <code>api/_core/config.php</code>.</li><li>Sign in with the temporary installation account, change its password, then create named operator accounts.</li><li>Add UPI/USDT details, payment images, turnover multiplier and withdrawal limits.</li><li>For JILI/JDB/Aviator, configure only official HTTPS merchant launch/callback credentials and keep secrets in server environment variables.</li></ol></div></section>
 <?php endif; endif;?>
 </div>
</main></div><script src="assets/admin.js?v=34"></script></body></html>
